### DISCUSSION TITLE
Weird issue with time being logged incorrectly

### DISCUSSION THREAD

**Discussion by andres-asm** [AnalogJ/scrutiny#889] [Issue Triage]
**Describe the bug**
I have three scrutiny instances now, 2 in unraid and another on an ubuntu server. 
I just noticed times are off in different ways in different servers

server1: unraid on an intel nuc
local time is 14:25 now

![image](https://user-images.githubusercontent.com/1721040/229210442-3973c7ca-dc53-45b6-816f-508012b2bc0a.png)

So temp is 5 hours into the future.
I checked the dates and smartctl on both the host and the container, both show the correct date

server2: unraid on an hp microserver gen8

This is even weirder I recreated the whole thing to start from scratch, once it started I got this
![image](https://user-images.githubusercontent.com/1721040/229210793-5338bdaa-cff8-467d-ac26-1d36646ac0bf.png)

So there are several samples already, all in the future
I checked the dates and smartctl on both the host and the container, both show the correct date

server3: ubuntu 18

![image](https://user-images.githubusercontent.com/1721040/229211100-d4ba4f86-88e9-4c6f-ae0b-7af06bbc947c.png)

same thing, and I did get several samples even though I nuked the container entirely
in this one, time was in fact different between container and host, I fixed that by adding these lines to the volumes part on the compose file, still the issue persists

```
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
```

**Expected behavior**
Dates should be correct and not in the future, 5 hours is in fact the difference between my localtime and GMT, but still this isn't correct

**Screenshots**

**Log Files**
Command for server 1
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='scrutiny' --net='bridge' --privileged=true -e TZ="America/Bogota" -e HOST_OS="Unraid" -e HOST_HOSTNAME="s3-unraid1" -e HOST_CONTAINERNAME="scrutiny" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:8081]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/scrutiny.png' -p '8081:8080/tcp' -v '/run/udev':'/run/udev':'ro' -v '/dev/disk':'/dev/disk':'ro' -v '':'/opt/scrutiny/config':'rw' -v '':'/opt/scrutiny/influxdb':'rw' -v '/etc/localtime':'/etc/localtime':'ro' 'ghcr.io/analogj/scrutiny:master-omnibus' 
```
Command for server 2
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='scrutiny' --net='bridge' --privileged=true -e TZ="America/Bogota" -e HOST_OS="Unraid" -e HOST_HOSTNAME="s4-unraid2" -e HOST_CONTAINERNAME="scrutiny" -l net.unraid.docker.managed=dockerman -l net.unraid.docker.webui='http://[IP]:[PORT:8081]' -l net.unraid.docker.icon='https://raw.githubusercontent.com/selfhosters/unRAID-CA-templates/master/templates/img/scrutiny.png' -p '8081:8080/tcp' -v '/run/udev':'/run/udev':'ro' -v '/dev/disk':'/dev/disk':'ro' -v '':'/opt/scrutiny/config':'rw' -v '':'/opt/scrutiny/influxdb':'rw' -v '/etc/localtime':'/etc/localtime':'ro' 'ghcr.io/analogj/scrutiny:master-omnibus'
```

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:beta-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./data/config:/opt/scrutiny/config
      - ./data/influxdb:/opt/scrutiny/influxdb
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
```

The log files will be available on your host in the `config` directory. Please attach them to this issue. 

Please also provide the output of `docker info`
