### DISCUSSION TITLE
[BUG] Disk paths must be lowercase to work

### DISCUSSION THREAD

**Discussion by jonathanjsimon** [AnalogJ/scrutiny#918] [Issue Triage]
**Describe the bug**
I've supplied devices to the container via the `/dev/disk/by-id/` paradigm so I can be sure the data tracks the right drive through reboots. All of these paths have uppercase for the make, model, and serial numbers. This matches my `collector.yaml`. However, scrutiny tries to scan these devices using a lowercased version of the path which, of course, does not work. I was able to work around it by mapping to lowercased drive names.

**Expected behavior**
Scrutiny should use the device paths provided exactly rather than altering them

This doesn't work
`composer.yaml`

```yaml
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    environment:
      - COLLECTOR_CRON_SCHEDULE="* * * * *"
    cap_add:
      - SYS_RAWIO
    ports:
      - "8989:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /path/to/scrutiny/config:/opt/scrutiny/config
      - /path/to/scrutiny/db:/opt/scrutiny/influxdb
    devices:
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED
      - /dev/disk/by-id/ata-WDC_WD102KFBX-68M95N0_REDACTED
      - /dev/disk/by-id/nvme-Samsung_SSD_950_PRO_256GB_REDACTED
      - /dev/disk/by-id/scsi-REDACTED
```

This does:
`compose.yaml`

```yaml
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    environment:
      - COLLECTOR_CRON_SCHEDULE="* * * * *"
    cap_add:
      - SYS_RAWIO
    ports:
      - "8989:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /path/to/scrutiny/config:/opt/scrutiny/config
      - /path/to/scrutiny/db:/opt/scrutiny/influxdb
    devices:
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-HGST_HUH721212ALE600_REDACTED:/dev/disk/by-id/ata-hgst_huh721212ale600_redacted
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED:/dev/disk/by-id/ata-toshiba_khk61rse480g_redacted
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED:/dev/disk/by-id/ata-toshiba_khk61rse480g_redacted
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED:/dev/disk/by-id/ata-toshiba_khk61rse480g_redacted
      - /dev/disk/by-id/ata-TOSHIBA_KHK61RSE480G_REDACTED:/dev/disk/by-id/ata-toshiba_khk61rse480g_redacted
      - /dev/disk/by-id/ata-WDC_WD102KFBX-68M95N0_REDACTED:/dev/disk/by-id/ata-wdc_wd102kfbx-68m95n0_redacted
      - /dev/disk/by-id/nvme-Samsung_SSD_950_PRO_256GB_REDACTED:/dev/disk/by-id/nvme-samsung_ssd_950_pro_256gb_redacted
      - /dev/disk/by-id/scsi-REDACTED:/dev/disk/by-id/scsi-redacted
```

**Log Files**

[scrutiny.log](https://github.com/user-attachments/files/20520918/scrutiny.log)
