### ISSUE TITLE
[FEAT] Ignore devices by type

### ISSUE THREAD

**Issue by auricom** [AnalogJ/scrutiny#110]
I run Scrutiny on a Kubernetes cluster, where it is not possible to passthrough devices to unprivileged containers. I'm running scrutiny with privileged: true. The scrutiny collector container see all the node devices, including the kubernetes volumes that are virtual devices (smartctl detect them as SCSI drives, as seen in smartctl --scan :
...
/dev/sdab -d scsi # /dev/sdab, SCSI device
/dev/sdad -d scsi # /dev/sdad, SCSI device
...

It would be great to ignore all devices from a specific type, in order to only gather data about physical devices.
As Kubernetes volumes are dynamically provisionned, I cannot create a list of specific devices to ignore.

The wanted collector configuration file would be like 

```
version: 1
devices:
  - type: 'nvme'
  - type: 'sat'
  - type: 'scsi'
    ignore: true
```
