### ISSUE TITLE
[BUG] Appears to ignore collector.yaml

### ISSUE THREAD

**Issue by ridizy** [AnalogJ/scrutiny#115]
**Describe the bug**
I'm running Scrutiny in a docker container on a Synology DS 1019+ running `DSM 6.2.3-25426 Update 2`.  By default, Scrutiny properly detects four of my drives.  One of my drives, the only WD Red, is not properly detected.  It requires the `'-d sat'` option, which I am passing via `collector.yaml`, but it appears that it is being ignored.

**Expected behavior**
I expect Scrutiny to use the `'-d sat'` option for `/dev/sdb` and then report the S.M.A.R.T. data properly

**Screenshots**
![image](https://user-images.githubusercontent.com/33641/97307026-8c3be180-1835-11eb-93ab-bf7dd49b30b4.png)

*collector.yaml*
```
version: 1
devices:
  # - device: /dev/sda
  #   type: 'sat'
  - device: /dev/sdb
    type: 'sat'
  # - device: /dev/sdc
  #   type: 'sat'
  # - device: /dev/sdd
  #   type: 'sat'
  # - device: /dev/sde
  #   type: 'sat'
  # - device: /dev/sdf
  #   type: 'sat'
```

**Log Files**
[collector.log](https://hastebin.com/ibajomukef.yaml)
*from Scrutiny container*
[smartctl -x -j /dev/sdb](https://hastebin.com/itujuwalej.json)
[smartctl -x -j /dev/sdb -d sat](https://hastebin.com/gozopegoqa.json)
