### ISSUE TITLE
Scrutiny and reverse proxy (traefik)

### ISSUE THREAD

**Issue by prov3it** [AnalogJ/scrutiny#136]
**Describe the bug**
I cant get scrutiny to work with a reverse proxy. Im having multiple services working with local en letsencrypt certificates and local and external domains, but scrutiny is one i cant get to work.

**Expected behavior**
i want to reach scrutiny over https://scrutiny.lan/

**my docker-compose.yaml:**
_note: i can reach scrutiny over port 1234 using IP._

```
version: "2.1"
services:
  scrutiny:
    image: analogj/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - DEBUG=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - COLLECTOR_DEBUG=true
      - SCRUTINY_DEBUG=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /mnt/usb/docker/config/scrutiny/config:/scrutiny/config
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    networks:
      - web
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
    ports:
      - 1234:8080
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scrutiny.entrypoints=websecure"
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.lan`)"
      - "traefik.http.routers.scrutiny.tls=true"
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"
      - "traefik.http.routers.scrutiny.tls.domains[0].main=scrutiny.lan"
      - "traefik.http.routers.scrutiny.middlewares=add-scry"
      - "traefik.http.middlewares.add-scry.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.add-scry.redirectregex.replacement=https://$$1/web/dashboard"

networks:
  web:
    external: true
```

_in another terminal trigger the collector_
_docker exec scrutiny scrutiny-collector-metrics run_

_then use docker cp to copy the log files out of the container._
_docker cp scrutiny:/tmp/collector.log collector.log_
_docker cp scrutiny:/tmp/web.log web.log__

Above does not work. The files don't exist.

**Comment by joe-eklund** [comment]
I am currently using traefik 1.7 in front of scrutiny using the hub/spoke paradigm and it is working. But I do have experience with traefik 2 for work, so I'll try to help.

Firstly, what is the error you get when you try to access scrutiny through traefik?

Do you see anything in traefik logs? Scrutiny logs?

You can check docker logs by typing `docker logs <container_name>` like `docker logs scrutiny`.

Are you able to ping the scrutiny container from traefik? That way you at least know if traefik can see the container it needs to proxy commands to.

To check this run:

1. `docker exec -it <your_traefik_container> /bin/sh`
2. `ping scrutiny`

What is your middleware `add-scry` doing? Why do you need those regex and replacement things for?

**Comment by prov3it** [comment]
Hi @joe-eklund, thanks for your comment.

> using the hub/spoke paradigm

What do you mean by that?

> Firstly, what is the error you get when you try to access scrutiny through traefik?

Bad Gateway

> Do you see anything in traefik logs? Scrutiny logs?

Traefik:
```
time="2021-01-11T13:20:57Z" level=debug msg="{\"success\":true}" bodyType=response clientIP=127.0.0.1 hostname=50d52fd73c90 latency=201 method=POST path=/api/device/0x50024e9205c168fd/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1
time="2021-01-11T13:20:57Z" level=info msg="Main: Completed" type=metrics
```
Scrutiny:
```
time="2021-01-11T13:20:57Z" level=debug msg="{\"success\":true}" bodyType=response clientIP=127.0.0.1 hostname=50d52fd73c90 latency=201 method=POST path=/api/device/0x50024e9205c168fd/smart referer= respLength=16 statusCode=200 userAgent=Go-http-client/1.1
time="2021-01-11T13:20:57Z" level=info msg="Main: Completed" type=metrics
```
and i see that the collector is running and doing its job.

> Are you able to ping the scrutiny container from traefik?
Yes. I tested it the way you provided.

as far as i know and understood, traefik doesnt handle redirects very well, so you have to help it. Thats how i got pihole running as well.

Edit: I think it has something to do with ipv6 since scrutiny is only listening on that socket. I had ipv6 disabled on my host, but i re-enabled it. Still no luck.

**Comment by modzilla99** [comment]
I don't use the metrics-collector with docker as I am on proxmox, but my web frontend is behind traefik in an lxc container and it works flawlessly. That's how I use it:

```yaml
    scrutiny:
        image: linuxserver/scrutiny
        restart: always
        container_name: scrutiny
        env_file:
            - /data/Docker/env/general.env
        environment:
            - SCRUTINY_WEB=true
            - SCRUTINY_COLLECTOR=false
        volumes:
            - /data/Docker/Scrutiny:/config
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.mydomain.com`)"
            - "traefik.http.routers.scrutiny.tls=true"
            - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"
```
