### ISSUE TITLE
[BUG] It didn't seem to be compatible with my RAID card: DELL or MegaRaid controller, please try adding '-d megaraid,N'

### ISSUE THREAD

**Issue by salamanders** [AnalogJ/scrutiny#155]
**Describe the bug**
Errors during startup, then no devices listed

        "string": "Smartctl open device: /dev/sda failed: DELL or MegaRaid controller, please try adding '-d megaraid,N'",
        "severity": "error"

**Expected behavior**
I have a RAID card, and ~18 drives (mix of SSD and regular).
I had the same issue when trying to run smartctl directly, and was able to get it to work by modifying the command.

**Log Files**
Attached.
[log.txt](https://github.com/AnalogJ/scrutiny/files/6191963/log.txt)

**Comment by salamanders** [comment]
Is this the same as issue #30 ?

**Comment by salamanders** [comment]
```
$ sudo smartctl --scan
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/sdc -d scsi # /dev/sdc, SCSI device
/dev/sdd -d scsi # /dev/sdd, SCSI device
/dev/bus/0 -d megaraid,0 # /dev/bus/0 [megaraid_disk_00], SCSI device
/dev/bus/0 -d megaraid,1 # /dev/bus/0 [megaraid_disk_01], SCSI device
/dev/bus/0 -d megaraid,2 # /dev/bus/0 [megaraid_disk_02], SCSI device
/dev/bus/0 -d megaraid,3 # /dev/bus/0 [megaraid_disk_03], SCSI device
/dev/bus/0 -d megaraid,4 # /dev/bus/0 [megaraid_disk_04], SCSI device
/dev/bus/0 -d megaraid,5 # /dev/bus/0 [megaraid_disk_05], SCSI device
/dev/bus/0 -d megaraid,6 # /dev/bus/0 [megaraid_disk_06], SCSI device
/dev/bus/0 -d megaraid,7 # /dev/bus/0 [megaraid_disk_07], SCSI device
```

**Comment by salamanders** [comment]
I also tried #88 but no luck.

`$ more /tmp/scrutiny-config/collector.yaml`

```
version: 1

devices:
  - device: /dev/sda
    type: 'scsi'

  - device: /dev/sdb
    type: 'scsi'

  - device: /dev/bus/0
    type:
      - megaraid,0
      - megaraid,1
      - megaraid,2
      - megaraid,3
      - megaraid,4
      - megaraid,5
      - megaraid,6
      - megaraid,7
      - megaraid,8
      - megaraid,9
      - megaraid,10


```
