### ISSUE TITLE
Add documentation for different deployment modes

### ISSUE THREAD

**Issue by AnalogJ** [AnalogJ/scrutiny#16]
- [x] All-in-one docker image
- [x] Manual installation (non-docker)
- [x] Separate Web + Collector images. 
- [ ] OS Specific packages.

**Comment by bbrendon** [comment]
machine A
```

# cat docker-compose.yaml
version: '3'
services:
  scrutiny:
    image: analogj/scrutiny
    volumes:
      - ./config:/scrutiny/config
    ports:
      - 8080:8080

```

machine B package.
`apt-get install -t buster-backports smartmontools`


machine B cron
```
33 10 * * *     root    /usr/local/sbin/scrutiny-collector-metrics-linux-amd64   run SCRUTINY_API_ENDPOINT=http://lily:8080 > /dev/null 2>&1
```
