### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wallacebrf** [AnalogJ/scrutiny#185]
i have scrutiny running in docker on one of my synology NAS devices as both a web/API and collector. that is working fine and it is seeing all 9x of the drives on that device. 

i am trying to get the collector configured on a second synology NAS and i cannot get the collector to send the data to the web/API on the first device

here is the result of running the collector manally:

```
docker exec analogj-scrutiny-collector /scrutiny/bin/scrutiny-collector-metrics run
2021/07/15 17:22:48 Loading configuration file: /scrutiny/config/collector.yaml

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                               dev-0.3.12

time="2021-07-15T17:22:48Z" level=info msg="Verifying required tools" type=metrics
time="2021-07-15T17:22:48Z" level=info msg="Executing command: smartctl --scan -j" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdea" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdea: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdec" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdec: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sded" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sded: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdee" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdee: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sda" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sda: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdb" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdb: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdeb" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdeb: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdc" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdc: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Executing command: smartctl --info -j -d sat /dev/sdd" type=metrics
time="2021-07-15T17:22:49Z" level=error msg="Could not retrieve device information for sdd: exit status 2" type=metrics
time="2021-07-15T17:22:49Z" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
2021/07/15 17:22:59 ERROR: Post "http://192.168.101.3:8080/api/devices/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

for some reason i am getting the error
`ERROR: Post "http://192.168.101.3:8080/api/devices/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

i am able to see the scrutiny web page fine at the designated address which shows the 9x drives on the first synology that is working. 

i have tried changing firewall settings (turned off entirely) but it will not work. 

any ideas?

here is the collector.yaml file for the collector that is not sending data to the web/API correctly
```
# Commented Scrutiny Configuration File
#
# The default location for this file is /scrutiny/config/collector.yaml.
# In some cases to improve clarity default values are specified,
# uncommented. Other example values are commented out.
#
# When this file is parsed by Scrutiny, all configuration file keys are
# lowercased automatically. As such, Configuration keys are case-insensitive,
# and should be lowercase in this file to be consistent with usage.


######################################################################
# Version
#
# version specifies the version of this configuration file schema, not
# the scrutiny binary. There is only 1 version available at the moment
version: 1

# The host id is a label used for identifying groups of disks running on the same host
# Primiarly used for hub/spoke deployments (can be left empty if using all-in-one image).
host:
  id: "ServerNVR"


# This block allows you to override/customize the settings for devices detected by
# Scrutiny via `smartctl --scan`
# See the "--device=TYPE" section of https://linux.die.net/man/8/smartctl
# type can be a 'string' or a 'list'
devices:
#  # example for forcing device type detection for a single disk
#  - device: /dev/sda
#    type: 'sat'
  - device: /dev/sdea
    type: 'sat'
  - device: /dev/sdeb
    type: 'sat'
  - device: /dev/sdec
    type: 'sat'
  - device: /dev/sded
    type: 'sat'
  - device: /dev/sdee
    type: 'sat'
  - device: /dev/sda
    type: 'sat'
  - device: /dev/sdb
    type: 'sat'
  - device: /dev/sdc
    type: 'sat'
  - device: /dev/sdd
    type: 'sat'
#
#  # example to show how to ignore a specific disk/device.
#  - device: /dev/sda
#    ignore: true
#
#  # examples showing how to force smartctl to detect disks inside a raid array/virtual disk
#  - device: /dev/bus/0
#    type:
#      - megaraid,14
#      - megaraid,15
#      - megaraid,18
#      - megaraid,19
#      - megaraid,20
#      - megaraid,21
#
#  - device: /dev/twa0
#    type:
#      - 3ware,0
#      - 3ware,1
#      - 3ware,2
#      - 3ware,3
#      - 3ware,4
#      - 3ware,5

log:
  file: '/scrutiny/config/log.txt' #absolute or relative paths allowed, eg. web.log
  level: INFO
#
api:
  endpoint: 'http://192.168.101.3:8080/'

########################################################################################################################
# FEATURES COMING SOON
#
# The following commented out sections are a preview of additional configuration options that will be available soon.
#
########################################################################################################################
```
