### ISSUE TITLE
[FEAT] [Docs] Document how to set up in rootless mode

### ISSUE THREAD

**Issue by subdavis** [AnalogJ/scrutiny#191]
**Is your feature request related to a problem? Please describe.**
Please document how to configure this correctly in rootless mode.

**Describe the solution you'd like**
Assuming I'm running 

And my docker-compose section looks something like this:

```yml

  scrutiny:
    image: analogj/scrutiny
    container_name: scrutiny
    restart: unless-stopped
    networks:
      - scrutiny-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=scrutiny-net
      - traefik.http.services.scrutiny-svc.loadbalancer.server.port=8080
      - traefik.http.routers.scrutiny-rtr.rule=Host(`scrutiny.${DNS_DOMAIN}`)
      - traefik.http.routers.scrutiny-rtr.entrypoints=websecure
      - traefik.http.routers.scrutiny-rtr.tls=true
      - traefik.http.routers.scrutiny-rtr.middlewares=traefik-forward-auth@docker
    volumes:
      - /run/udev:/run/udev:ro
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdd
```

What am I missing?  Some modification to `/etc/sysctl.conf` perhaps?

**Additional context**

Here's the error I'm getting:

```
err: ERROR: for scrutiny  Cannot start service scrutiny: OCI runtime create failed: 
  container_linux.go:370: starting container process caused: process_linux.go:459: 
    container init caused: rootfs_linux.go:59: 
      mounting "/run/udev" to rootfs at "/home/******/.local/share/docker/overlay2/8d3a13bc2b25daa3cda32f8e50bbf77f6e30db366d38d850aa9bbd0238dbc044/merged/run/udev" caused: 
        operation not permitted: unknown
```

**Comment by ericlathrop** [comment]
I've set up Scrutiny using the hub-and-spoke method with docker compose. The web container is easy to make work as a normal non-root user, but the collector container has problems with cron running into permissions problems. Here's my docker-compose.yml:

```
version: '3.7'

services:

  scrutiny-collector:
    environment:
      SCRUTINY_API_ENDPOINT: http://scrutiny-web:8080
    image: analogj/scrutiny:v0.3.12-collector
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/nvme0"
    networks:
      - internal_network
    restart: always
    # user: "1000:1000"
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/scrutiny/config

  scrutiny-web:
    image: analogj/scrutiny:v0.3.12-web
    labels:
      traefik.docker.network: web
      traefik.enable: "true"
    networks:
      - web
      - internal_network
    restart: always
    user: "1000:1000"
    volumes:
      - ./config:/scrutiny/config

networks:
  web:
    external: true
  internal_network:
    internal: true
```
