### ISSUE TITLE
[BUG] Didn't get notified of 'Percentage Used' failed status on NVMe drives

### ISSUE THREAD

**Issue by FingerlessGlov3s** [AnalogJ/scrutiny#203]
**Describe the bug**
I unfortunately just had two NVMe drives die at the same time due to wear. I had both of the drive monitored in Scrutiny but I didn't get alerted for the failed status of the Percentage Used. No real harm done, everything was backed up.

When the drive hit 100 Percentage Used (sometimes called SSD Wear), I wasn't notified to say the SSD maybe about to die, or the status has changed.

NVMe1 was 130% and NVMe2 was 104%

Scrutiny Web runs in docker and the collectors run on the bare metal servers. 

**Expected behaviour**
I should of notified me via telegram and email, but never happened.

**Screenshots**
![image](https://user-images.githubusercontent.com/3495647/142713646-3ca52f5c-5ad1-4e6f-86ed-1e775045e1b8.png)

**Log Files**
Unable to run collector on these NVMe drives as they have been replaced and I no longer have access to them.
I do have SMART data from the dead NVMe drive but the screenshot shows the data was coming through over 100 percent.

**Scrutiny Web Config**
```
version: 1

web:
  listen:
    port: 8080
    host: 0.0.0.0
  database:
    location: /scrutiny/config/scrutiny.db
  src:
    frontend:
      path: /scrutiny/web
#log:
#  file: '' #absolute or relative paths allowed, eg. web.log
#  level: Debug

notify:
  urls:
    - "telegram://1234657891:redacted@telegram?channels=-1234657891"
    - "smtp://mail.domain.com:587/?fromAddress=scrutiny@domain.com&toAddresses=fingerlessgloves@domain.com"
```
