### ISSUE TITLE
Documentation regarding "collect" in config file

### ISSUE THREAD

**Issue by milindpatel63** [AnalogJ/scrutiny#206]
I am running scrutiny in docker on Ubuntu 20.04. By default the "long" and "short" commands of "collect" flag is disabled.

```
collect:
  metric:
    enable: true
    command: '-a -o on -S on'
  long:
    enable: false
    command: ''
  short:
    enable: false
    command: ''
```
What are this short and long for? Is it the same as running short and extended SMART check.
Should I enable them?
If not, then by default does the drive runs short SMART test at regular intervals on it's own?
