### ISSUE TITLE
HPE Smart Array P420i - no drives detected

### ISSUE THREAD

**Issue by Kegelcizer** [AnalogJ/scrutiny#213]
I've got 2 raid 1 arrays, 2 disks each.

Using the docker version, I gave it the drives /dev/sda and /dev/sdb that I've gathered with lsblk.

Then I ran docker exec scrutiny /scrutiny/bin/scrutiny-collector-metrics run, the webpage gives the same message that I need to run the collector.

Inside the container smartctl --scan returns nothing.

But if I run smartctl with "cciss,0-3", I can see all my 4 disks, in the container and in the host.

I'd appreciate any help! Thank you.

**Comment by rarobert** [comment]
I was able to read drives from my P420i in raid, and my P222 in HBA, by modifying the collector.yaml file. 

The example.collector.yaml file is a good start, but you just want to add something like this (modifying devices as required).
```
devices:
    - device: /dev/sda
      type:
        - 'cciss,0'
        - 'cciss,1'
    - device: /dev/sdb
      type:
        - 'cciss,0'
        - 'cciss,1'
```

Upload the collector.yaml to your persistent 'scrutiny/config' directory and restart the container, drives should appear automatically.
