### ISSUE TITLE
[BUG] unauthorized access

### ISSUE THREAD

**Issue by henfri** [AnalogJ/scrutiny#241]
**Describe the bug**
When starting the scrutiny container for the 2nd time (1st time was ok), I get this error:
```
scrutiny    | Start the scrutiny server
scrutiny    | [GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
scrutiny    |  - using env:     export GIN_MODE=release
scrutiny    |  - using code:    gin.SetMode(gin.ReleaseMode)
scrutiny    |
scrutiny    | time="2022-05-10T19:34:49Z" level=info msg="Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n"
scrutiny    | time="2022-05-10T19:34:49Z" level=info msg="Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n"
scrutiny    | ts=2022-05-10T19:34:49.153391Z lvl=info msg=Unauthorized log_id=0aNsJ9F0000 error="authorization not found"
scrutiny    | panic: unauthorized: unauthorized access
scrutiny    |
scrutiny    | goroutine 1 [running]:
scrutiny    | github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x129f900, 0xc000010d10, 0x12a4ae0, 0xc000344690, 0x129f980)
scrutiny    |   /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
scrutiny    | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000337080, 0x12a4ae0, 0xc000344690, 0x14)
scrutiny    |   /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
scrutiny    | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000337080, 0x0, 0x0)
scrutiny    |   /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
scrutiny    | main.main.func2(0xc00034c100, 0x4, 0x6)
scrutiny    |   /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
scrutiny    | github.com/urfave/cli/v2.(*Command).Run(0xc000347560, 0xc00029ff80, 0x0, 0x0)
scrutiny    |   /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
scrutiny    | github.com/urfave/cli/v2.(*App).RunContext(0xc00027c300, 0x128e800, 0xc000036030, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
scrutiny    |   /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
scrutiny    | github.com/urfave/cli/v2.(*App).Run(...)
scrutiny    |   /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
scrutiny    | main.main()
scrutiny    |   /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x65a
```

**Expected behavior**
No "unauthorized access" error

**Screenshots**
N/A

**Log Files**
See above

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    ports:
      - "89:8080"
    volumes:
      - /run/udev:/run/udev:ro
      - /srv/Daten/dockerconfig/scrutiny/config:/opt/scrutiny/config
      - /srv/Daten/dockerconfig/scrutiny/influxdb:/var/lib/influxdb2
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
      - "/dev/sdg"
      - "/dev/sdh"
```
What could be the reason for this?

Best regards,
Hendrik

**Comment by AnalogJ** [comment]
can you confirm that your `/srv/Daten/dockerconfig/scrutiny/config` directory contains a `scrutiny.yaml` file?
Does the file have a `web.influxdb.token` key?

**Comment by shamoon** [comment]
I got this bug when try to restore from a backup (I just duplicated `/config` and `/influxdb` dirs), my yaml does contain the token, not sure next best move, thank you

**Comment by AnalogJ** [comment]
can you shut down the service, then edit the docker-compose.yaml file to add a new port mapping:

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    ports:
      - "89:8080"
      - "8086:8086"
    volumes:
      - /run/udev:/run/udev:ro
      - /srv/Daten/dockerconfig/scrutiny/config:/opt/scrutiny/config
      - /srv/Daten/dockerconfig/scrutiny/influxdb:/var/lib/influxdb2
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
      - "/dev/sdg"
      - "/dev/sdh"

```

when you visit `http://server_name_here:8086` you should see a login page for the InfluxDB. Login with `admin` and `password12345` as the username and password. 
Then you can view the admin token and verify that it matches the one in your config file:

![image](https://user-images.githubusercontent.com/891875/167732397-dbf95ec2-2cdb-4484-b293-c992626233fd.png)
