### ISSUE TITLE
[BUG] Connection refused connecting to the influxdb2 database

### ISSUE THREAD

**Issue by martini1992** [AnalogJ/scrutiny#242]
**Describe the bug**
Connection refused connecting to the influxdb2 database

Additionally to the below docker compose file I ahve also tried to connect directly to the container by name without exposing the infuxdb2 port externally, docker correctly determines the internal docker network IP but I still get connection refused.

Logs from the influxdb2 container indicate it is starting correctly and listening on the port 8086.

**Expected behaviour**
Some sort of confirmation that the web component has connected to the influxdb2 database

**Log Files**
log from docker log for web component
```panic: Post http://0.0.0.0:8086/api/v2/setup: dial tcp 0.0.0.0:8086: connect: connection refused```

docker compose file
```
version: '3.3'
services:
  scrutiny-web:
    ports:
      - 20000:8080
    volumes:
      - '/mnt/scrutiny/config:/opt/scrutiny/config'
    image: 'ghcr.io/analogj/scrutiny:beta-web'
    depends_on:
      - scrutiny-db

  scrutiny-db:
    ports:
      - 8086:8086
    volumes:
      - '/mnt/scrutiny/db:/var/lib/influxdb2'
    image: influxdb:2.2
```

**Additional Info**
Architecture: x86_64

**Comment by AnalogJ** [comment]
since you're using the `web` only container, the default influxdb hostname needs to be configured (`0.0.0.0` is incorrect). 

You'll need to edit your config file to look like:

```yaml

web:
  ....
  influxdb:
    host: 'scrutiny-db'
    port: 8086
    token: 'xxxxxx'
    retention_policy: true
```

Alternatively, you could set the influxdb hostname using the following environmental variable:

`SCRUTINY_WEB_INFLUXDB_HOST=scrutiny-db`

**Comment by martini1992** [comment]
OK now I have...
```
version: '3.3'
services:
  scrutiny-web:
    ports:
      - 20000:8080
    volumes:
      - '/mnt/scrutiny/config:/opt/scrutiny/config'
    image: 'ghcr.io/analogj/scrutiny:beta-web'
    depends_on:
      - scrutiny-db

  scrutiny-db:
    volumes:
      - '/mnt/scrutiny/db:/var/lib/influxdb2'
    image: influxdb:2.2
```

And the sample config file except for...

```
influxdb:
#    host: 0.0.0.0 
    host: scrutiny-db
    port: 8086
#    port: 20001
#    token: 'my-token'
#    org: 'my-org'
#    bucket: 'bucket'
```

And I'm still getting the connection refused but for the correct docker internal IP, are the token, org and bucket required?

**Comment by martini1992** [comment]
Think I've figured it out, even though I'm using depends_on Scrutiny was starting too quickly.
That and allowing the port through to the host and running through the initial setup.
After that I removed the port passthrough again.

**Comment by martini1992** [comment]
What I would suggest is adding some code to retry connecting a few times with a few seconds delay between.

**Comment by AnalogJ** [comment]
Hey @martini1992 

Here's a working example, with built in healthchecks. The `version '2.4'` line is required, as `depends_on.*.condition` is removed in later versions of docker-compose syntax. 

```yaml
version: '2.4'

services:
  influxdb:
    image: influxdb:2.2
    ports:
      - '8086:8086'
    volumes:
      - './influxdb:/var/lib/influxdb2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20


  web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    ports:
      - '8080:8080'
    volumes:
      - './config:/opt/scrutiny/config'
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s

  collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    cap_add:
      - SYS_RAWIO
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: 'http://web:8080'
    depends_on:
      web:
        condition: service_healthy
    devices:
      - "/dev/sda"
      - "/dev/sdb"
```

Im going to close this issue, but feel free to reopen if you run into any other issues.
