### ISSUE TITLE
[BUG] Latest image crashes on startup

### ISSUE THREAD

**Issue by tommyalatalo** [AnalogJ/scrutiny#248]
I just switched over to the docker images `ghcr.io/analogj/scrutiny:master-web` and `ghcr.io/analogj/scrutiny:master-collector` since the docker hub ones have been taken down. Now my `web` instance is crashing on startup with this error message:

```
goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x129f920, 0xc00038a070, 0x12a4b00, 0xc0003faa80, 0x129f9a0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000385610, 0x12a4b00, 0xc0003faa80, 0x1)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000385610, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
main.main.func2(0xc000387340, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc0003ef200, 0xc0003871c0, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc0003fe000, 0x128e820, 0xc0000c8010, 0xc0000be020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x65a
2022/05/13 14:38:05 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
time="2022-05-13T14:38:05Z" level=info msg="Trying to connect to scrutiny sqlite db: \n"
time="2022-05-13T14:38:05Z" level=info msg="Successfully connected to scrutiny sqlite db: \n"
panic: a username and password is required for a setup
```

There is no mention in the readme or the examble configs of a username/password, so what are the credentials that the application is missing and crashing over? Also, this error feels a lot like something that should be handled by the application and an informative error presented to the user.

**Comment by AnalogJ** [comment]
Hey, 
We've seen this before for users migrating from the LSIO image to the official omnibus image. 

Can you paste your docker run command or docker-compose file?

**Comment by tommyalatalo** [comment]
> Hey, We've seen this before for users migrating from the LSIO image to the official omnibus image.
> 
> Can you paste your docker run command or docker-compose file?

I don't use docker cli or docker-compose, I'm running it on Nomad, but here is the file anyway:
```
variable "web_image" {
  type    = string
  default = "ghcr.io/analogj/scrutiny:master-web"
}

variable "collector_image" {
  type    = string
  default = "ghcr.io/analogj/scrutiny:master-collector"
}

job "scrutiny" {
  datacenters = ["main"]
  type        = "service"

  vault {
    policies    = ["scrutiny"]
    change_mode = "restart"
  }

  group "api" {
    constraint {
      attribute = "${node.unique.name}"
      value     = "nas"
    }

    network {
      mode = "bridge"
      port "http" {
        to = 8080
      }
    }

    task "scrutiny" {
      driver = "docker"


      config {
        image   = var.web_image
        cap_add = ["sys_admin", "sys_rawio"]
        ports   = ["http"]

        volumes = [
          "/run/udev:/run/udev:ro",
          "secrets/scrutiny.yaml:/opt/scrutiny/config/scrutiny.yaml",
          "/zpool/services/scrutiny/scrutiny.db:/scrutiny/config/scrutiny.db",
        ]
      }

      service {
        name = "${NOMAD_TASK_NAME}"
        port = "http"

        tags = [
          "api",
          "http",
          "traefik.enable=true",
          "traefik.http.routers.https-${NOMAD_TASK_NAME}.entrypoints=https",
          "traefik.http.routers.https-${NOMAD_TASK_NAME}.rule=Host(`${NOMAD_TASK_NAME}.tox.sh`)",
          "traefik.http.routers.https-${NOMAD_TASK_NAME}.middlewares=chain-internal-no-auth@file",
          "traefik.http.routers.https-${NOMAD_TASK_NAME}.tls=true",
        ]

        check {
          port     = "http"
          name     = "${NOMAD_TASK_NAME} health"
          type     = "http"
          path     = "/api/health"
          interval = "30s"
          timeout  = "1s"
        }
      }

      env {
        GIN_MODE              = "release"
        SCRUTINY_API_ENDPOINT = "http://localhost:8080"
        SCRUTINY_COLLECTOR    = "false"
        SCRUTINY_WEB          = "true"
      }


      template {
        destination = "secrets/scrutiny.yaml"
        change_mode = "restart"
        data        = file("./config/scrutiny/scrutiny.yaml")
      }
    }
  }

  group "collector-arch" {
    constraint {
      attribute = "${node.unique.name}"
      value     = "arch"
    }

    network {
      mode = "bridge"
    }

    task "wait-for-api" {
      driver = "docker"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        image   = "praqma/network-multitool:alpine-extra"
        command = "/bin/bash"

        args = [
          "-c",
          "while ! dig +short api.scrutiny.service.consul srv | grep -ve '^$'; do sleep 1; done",
        ]
      }
    }

    task "collector" {
      driver = "docker"

      config {
        image   = var.collector_image
        cap_add = ["sys_admin", "sys_rawio"]

        volumes = [
          "/run/udev:/run/udev:ro",
          "secrets/collector.yaml:/opt/scrutiny/config/collector.yaml",
        ]

        devices = [
          {
            host_path      = "/dev/sda"
            container_path = "/dev/sda"
          },
          {
            host_path      = "/dev/sdb"
            container_path = "/dev/sdb"
          },
          {
            host_path      = "/dev/sdc"
            container_path = "/dev/sdc"
          },
          {
            host_path      = "/dev/sdd"
            container_path = "/dev/sdd"
          },
          {
            host_path      = "/dev/sde"
            container_path = "/dev/sde"
          },
          {
            host_path      = "/dev/sdf"
            container_path = "/dev/sdf"
          },
        ]
      }

      template {
        destination = "secrets/collector.yaml"
        change_mode = "restart"
        data        = file("./config/scrutiny/collector.yaml")
      }
    }
  }

  group "collector-backup" {
    constraint {
      attribute = "${node.unique.name}"
      value     = "backup"
    }

    network {
      mode = "bridge"
    }

    task "wait-for-api" {
      driver = "docker"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        image   = "praqma/network-multitool:alpine-extra"
        command = "/bin/bash"

        args = [
          "-c",
          "while ! dig +short api.scrutiny.service.consul srv | grep -ve '^$'; do sleep 1; done",
        ]
      }
    }

    task "collector" {
      driver = "docker"

      config {
        image   = var.collector_image
        cap_add = ["sys_admin", "sys_rawio"]

        volumes = [
          "/run/udev:/run/udev:ro",
          "secrets/collector.yaml:/opt/scrutiny/config/collector.yaml",
        ]

        devices = [
          {
            host_path      = "/dev/nvme0"
            container_path = "/dev/nvme0"
          },
          {
            host_path      = "/dev/sda"
            container_path = "/dev/sda"
          },
          {
            host_path      = "/dev/sdb"
            container_path = "/dev/sdb"
          },
        ]
      }

      template {
        destination = "secrets/collector.yaml"
        change_mode = "restart"
        data        = file("./config/scrutiny/collector.yaml")
      }
    }
  }
  group "collector-nas" {
    constraint {
      attribute = "${node.unique.name}"
      value     = "nas"
    }

    network {
      mode = "bridge"
    }

    task "wait-for-api" {
      driver = "docker"

      lifecycle {
        hook    = "prestart"
        sidecar = false
      }

      config {
        image   = "praqma/network-multitool:alpine-extra"
        command = "/bin/bash"

        args = [
          "-c",
          "while ! dig +short api.scrutiny.service.consul srv | grep -ve '^$'; do sleep 1; done",
        ]
      }
    }

    task "collector" {
      driver = "docker"

      config {
        image   = var.collector_image
        cap_add = ["sys_admin", "sys_rawio"]

        volumes = [
          "/run/udev:/run/udev:ro",
          "secrets/collector.yaml:/opt/scrutiny/config/collector.yaml",
        ]

        devices = [
          {
            host_path      = "/dev/nvme0"
            container_path = "/dev/nvme0"
          },
          {
            host_path      = "/dev/sda"
            container_path = "/dev/sda"
          },
          {
            host_path      = "/dev/sdb"
            container_path = "/dev/sdb"
          },
          {
            host_path      = "/dev/sdc"
            container_path = "/dev/sdc"
          },
          {
            host_path      = "/dev/sdd"
            container_path = "/dev/sdd"
          },
          {
            host_path      = "/dev/sde"
            container_path = "/dev/sde"
          },
          {
            host_path      = "/dev/sdf"
            container_path = "/dev/sdf"
          },
        ]
      }

      template {
        destination = "secrets/collector.yaml"
        change_mode = "restart"
        data        = file("./config/scrutiny/collector.yaml")
      }
    }
  }
}
```

**Comment by evulhotdog** [comment]
@AnalogJ  here's mine as well.

```
---
version: "2.1"
services:
  scrutiny:
    image: linuxserver/scrutiny
    container_name: scrutiny
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - ./config:/config
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    restart: unless-stopped
    networks:
      - internet-facing

networks:
  internet-facing:
    external:
      name: internet-facing
```

**Comment by AnalogJ** [comment]
@tommyalatalo you'll need to remove the `SCRUTINY_WEB=true` and `SCRUTINY_COLLECTOR=true` environmental variables. They were used by the LSIO image, but cause issues with Scrutiny for some reason. 

@evulhotdog  you'll need to remove the same environmental variables I mentioned to @tommyalatalo , but you'll also need to update your image to `ghcr.io/analogj/scrutiny:master-omnibus`. The LSIO image is missing a new dependency that we introduced in v0.4.0+ (InfluxDB), and that causes issues. You can revert to a earlier version of the LSIO image ( `lscr.io/linuxserver/scrutiny:060ac7b8-ls34`), or just change to the official Scrutiny image (`ghcr.io/analogj/scrutiny:master-omnibus`)

I'm going to close this issue for now, feel free to comment/reopen it if you run into any other issues.

**Comment by tommyalatalo** [comment]
Removing `SCRUTINY_WEB` and `SCRUTINY_COLLECTOR` don't fix the problem, it now seems like the scrutiny app in the api container can't connect to the internal influxdb instance:

```
goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x129f920, 0xc0000b0098, 0x12a4b00, 0xc000414bd0, 0x129f9a0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc0000ad6c0, 0x12a4b00, 0xc000414bd0, 0x10)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc0000ad6c0, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
main.main.func2(0xc0000b7340, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc0004170e0, 0xc0000b71c0, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc00009a300, 0x128e820, 0xc000038038, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x65a
2022/05/14 22:23:57 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
time="2022-05-14T22:23:57Z" level=info msg="Trying to connect to scrutiny sqlite db: /scrutiny/config/scrutiny.db\n"
time="2022-05-14T22:23:57Z" level=info msg="Successfully connected to scrutiny sqlite db: /scrutiny/config/scrutiny.db\n"
panic: Post "http://0.0.0.0:8086/api/v2/setup": dial tcp 0.0.0.0:8086: connect: connection refused
```

**Comment by tommyalatalo** [comment]
So now I switched to the omnibus image on my api node, but it also fails...
The container just loops with the below message over and over, though I can see that influxdb is running and listening on 8086 inside, and I've set `SCRUTINY_WEB_INFLUXDB_HOST="http://localhost:8086"`

```
 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                             dev-0.4.4

Start the scrutiny server
waiting for influxdb
starting scrutiny
```

**Comment by AnalogJ** [comment]
Hey @tommyalatalo can you unset the `SCRUTINY_WEB_INFLUXDB_HOST` variable? its unnecessary, as the defaults should work: `SCRUTINY_WEB_INFLUXDB_HOST=0.0.0.0`

**Comment by AnalogJ** [comment]
actually, can you try setting it to `SCRUTINY_WEB_INFLUXDB_HOST=localhost` if unsetting the env var doesnt work.

**Comment by raulfg3** [comment]
same problem here with latest docker:

yesterday at 17:25:48
yesterday at 17:25:48 ___   ___  ____  __  __  ____  ____  _  _  _  _
yesterday at 17:25:48/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
yesterday at 17:25:48\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
yesterday at 17:25:48(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
yesterday at 17:25:48github.com/AnalogJ/scrutiny                             dev-0.4.4
yesterday at 17:25:48
yesterday at 17:25:48Start the scrutiny server
yesterday at 17:25:48[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
yesterday at 17:25:48 - using env:	export GIN_MODE=release
yesterday at 17:25:482022/05/14 17:25:48 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.
yesterday at 17:25:48time="2022-05-14T17:25:48+02:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"
yesterday at 17:25:48 - using code:	gin.SetMode(gin.ReleaseMode)
yesterday at 17:25:48
yesterday at 17:25:48time="2022-05-14T17:25:48+02:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"
yesterday at 17:25:48panic: a username and password is required for a setup
yesterday at 17:25:48
yesterday at 17:25:48goroutine 1 [running]:
yesterday at 17:25:48github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0xfeaac0, 0xc0000c4cd8}, {0xff3d50, 0xc000373f10})
yesterday at 17:25:48	/app/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5
yesterday at 17:25:48github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000370610, {0xff3d50, 0xc000373f10})
yesterday at 17:25:48	/app/scrutiny/webapp/backend/pkg/web/server.go:26 +0xb4
yesterday at 17:25:48github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000370610)
yesterday at 17:25:48	/app/scrutiny/webapp/backend/pkg/web/server.go:97 +0x3ab
yesterday at 17:25:48main.main.func2(0xc00034fb80)
yesterday at 17:25:48	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7
yesterday at 17:25:48github.com/urfave/cli/v2.(*Command).Run(0xc000359e60, 0xc00034fa00)
yesterday at 17:25:48	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x64a
yesterday at 17:25:48github.com/urfave/cli/v2.(*App).RunContext(0xc000240480, {0xfd4dd0, 0xc0000cc000}, {0xc0000c8000, 0x2, 0x2})
yesterday at 17:25:48	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x926
yesterday at 17:25:48github.com/urfave/cli/v2.(*App).Run(...)
yesterday at 17:25:48	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
yesterday at 17:25:48main.main()
yesterday at 17:25:48	/app/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679



It woorks fine until latest docker update.

**Comment by raulfg3** [comment]
- 
version: "2.1"
2
networks:
3
  default:
4
    external:
5
      name: my-net
6
services:
7
  scrutiny:
8
    image: ghcr.io/linuxserver/scrutiny
9
    container_name: scrutiny
10
    cap_add:
11
      - SYS_RAWIO
12
      - SYS_ADMIN #optional
13
    environment:
14
      - PUID=1001
15
      - PGID=1000
16
      - TZ=Europe/Madrid
17
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
18
      - SCRUTINY_WEB=true
19
      - SCRUTINY_COLLECTOR=true
20
    volumes:
21
      - /srv/dev-disk-by-uuid-6f38f974-7aec-452a-815d-9101878af2e1/Data/dockers/scrutiny:/config
22
      - /run/udev:/run/udev:ro
23
    ports:
24
      - 89:8080
25
    devices:
26
      - /dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B7282A5358D:/dev/sda
27
      - /dev/disk/by-id/ata-WDC_WD10EADS-00L5B1_WD-WCAU46188971:/dev/sdb
28
      - /dev/disk/by-id/ata-ST10000VN0004-1ZD101_ZA29Z6HM:/dev/sdc
29
      - /dev/disk/by-id/ata-ST10000VN0004-1ZD101_ZA28D436:/dev/sdd
30
      - /dev/disk/by-id/ata-ST10000VN0004-1ZD101_ZA2ARA9E:/dev/sde
31
      - /dev/disk/by-id/ata-ST10000VN0004-1ZD101_ZA29ZCZ2:/dev/sdf
32
    restart: unless-stopped
Webhooks
Create a Stack webhook

**Comment by raulfg3** [comment]
```
version: "2.1"
networks:
  default:
    external:
      name: my-net
services:
  scrutiny:
    image: ghcr.io/linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1001
      - PGID=1000
      - TZ=Europe/Madrid
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /srv/dev-disk-by-uuid-6f38f974-7aec-452a-815d-9101878af2e1/Data/dockers/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 89:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
    restart: unless-stopped
```

**Comment by raulfg3** [comment]
I switched for latest analogj Image and worrks fine, my new yaml file is: 

```
version: "3.5"
networks:
  default:
    external:
      name: my-net
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    volumes:
      - /srv/dev-disk-by-uuid-6f38f974-7aec-452a-815d-9101878af2e1/Data/dockers/scrutiny:/opt/scrutiny/config
      - /srv/dev-disk-by-uuid-6f38f974-7aec-452a-815d-9101878af2e1/Data/dockers/scrutiny/influxdb:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    ports:
      - 89:8080 # webapp
      - 86:8086 # influxDB admin
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
    restart: unless-stopped
```
