### ISSUE TITLE
[FEAT] Add Instructions for Bring-your-own-InfluxDB with restricted access token

### ISSUE THREAD

**Issue by jnaav** [AnalogJ/scrutiny#249]
I want to use my existing influxdb in the same server, but it is not working and I need some help. 

This is my compose file:

```
 scrutiny:
   image: ghcr.io/analogj/scrutiny:master-omnibus
   container_name: scrutiny
   cap_add:
     - SYS_RAWIO
   volumes:
     - /docker/scrutiny:/opt/scrutiny/config
     - /run/udev:/run/udev:ro
   ports:
     - 8017:8080
   devices:
     - /dev/sda:/dev/sda
     - /dev/sdb:/dev/sdb
     - /dev/sdc:/dev/sdc
     - /dev/sdd:/dev/sdd
     - /dev/sde:/dev/sde
   restart: unless-stopped   
```

This is my scrutiny.yaml file

```
log:
  file: ""
  level: INFO
notify:
  urls: []
web:
  database:
    location: /opt/scrutiny/config/scrutiny.db
  influxdb:
    bucket: scrutiny
    host: MY-SERVER-LOCAL-IP
    org: MYORG
    port: "8086"
    retention_policy: true
    token: MY-TOKEN
  listen:
    basepath: ""
    host: 0.0.0.0
    port: "8080"
  src:
    frontend:
      path: /opt/scrutiny/web
```

I have configured a new bucket in my influxdb instance called scrutiny and a new API token with read and write permissions in that bucket. 

In logs, there is this error:

```
panic: organization 'MYORG' not found

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware(0x129f920, 0xc000408088, 0x12a4b00, 0xc000471650, 0x129f9a0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xe6
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000405ad0, 0x12a4b00, 0xc000471650, 0x14)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xd8
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000405ad0, 0x0, 0x0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:97 +0x234
main.main.func2(0xc00040f400, 0x4, 0x6)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc0004737a0, 0xc00040f280, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunContext(0xc000484000, 0x128e820, 0xc000130010, 0xc000126020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x65a
```

It seems it cannot found my organization? The name is correct, I have other services working fine with that influxedb instance. 

I am missing something?
