### ISSUE TITLE
[BUG] 0.4 beta collector only logging data at 10pm, 11pm, 12am, 1am

### ISSUE THREAD

**Issue by martini1992** [AnalogJ/scrutiny#252]
**Describe the bug**
 0.4 beta collector only logging data at 10pm, 11pm, 12am, 1am

**Expected behavior**
Logs every hour

**Log Files**
Nothing of in logs, collector gets triggered at midnight by cron as expected.

My setup as discussed before is the docker hub spoke, web and influx on an x86-64 server and collector on an armhf NAS.

**Comment by AnalogJ** [comment]
The collector cron issue was fixed last night. Can you try the master collector image or the v0.4.5 collector image?

**Comment by martini1992** [comment]
Using the master branch collector and the issue is still there.

**Comment by AnalogJ** [comment]
@martini1992 can you paste your Docker-compose file? By default the cron job is scheduled to run once a day, I'm guessing you customized it via the environmental variable?

**Comment by martini1992** [comment]
```
version: '3.3'                                                                                  services:
  scrutiny-collector:
    volumes:
      - '/run/udev:/run/udev:ro'
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    environment:
      - 'COLLECTOR_API_ENDPOINT=REDACTED'
    image: 'ghcr.io/analogj/scrutiny:master-collector'
```
