### ISSUE TITLE
Clarification of volume permissions?

### ISSUE THREAD

**Issue by mrhotio** [AnalogJ/scrutiny#26]
What is the reason for the volume `/dev/disk` having to need write permissions, instead of mounting it read-only?

**Comment by AnalogJ** [comment]
Hey @hotio 

Honestly its because I haven't yet had time to verify that it works with read-only. I have a story tracking the use of `--privileged` and the volume mounts, replacing them with `--cap-add` and `--device` calls instead: https://github.com/AnalogJ/scrutiny/issues/18

I've just been busy with other features (like notifications & better device detection) so I haven't had time to work on that yet.

**Comment by Derkades** [comment]
It seems to work fine for me with `:ro`

**Comment by AnalogJ** [comment]
Good news @Derkades @hotio @kinghat

I just did a quick test replacing `--privileged` and `-v /dev/disk:/dev/disk` with `--device` and `--cap-add` -- and it **seems** like everything still works. 
I need to do some more extensive testing, but it would be awesome if you could verify that the scrutiny dashboard is still working for you:

```
docker run --rm \
-p 8080:8080 \
--cap-add SYS_RAWIO \
--device=/dev/sda \
--device=/dev/sdb \
-v /run/udev:/run/udev:ro \
--name scrutiny \
 analogj/scrutiny:smartctl_scan
```

Note: you'll need to add `--device=/dev/sd*` lines for each of your hard disk devices. Also, please use the `analogj/scrutiny:smartctl_scan` image, as it's running the latest code (with new device detection code).

**Comment by mrhotio** [comment]
The last commit from master (same for the smartctl_scan tag) has completely broken nvme output for me
![image](https://user-images.githubusercontent.com/26902309/93758832-6c4b4980-fc09-11ea-9e16-f77c74c6ed8e.png)

**Comment by mrhotio** [comment]
`--cap-add SYS_RAWIO` for nvme drives doesn't provide sufficient permissions

```
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      0
    ],
    "svn_revision": "4883",
    "platform_info": "x86_64-linux-5.4.0-47-generic",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-a",
      "-j",
      "-d",
      "nvme",
      "/dev/nvme1"
    ],
    "messages": [
      {
        "string": "Read NVMe Identify Controller failed: NVME_IOCTL_ADMIN_CMD: Permission denied",
        "severity": "error"
      }
    ],
    "exit_status": 2
  },
  "device": {
    "name": "/dev/nvme1",
    "info_name": "/dev/nvme1",
    "type": "nvme",
    "protocol": "NVMe"
  }
}
```

**Comment by mrhotio** [comment]
`--cap-add SYS_ADMIN` does provide sufficient perms, but isn't as restrictive from what I can gather

**Comment by AnalogJ** [comment]
Yeah, my understanding is that `--cap-add SYS_ADMIN` is basically the equivalent of `--privileged` https://man7.org/linux/man-pages/man7/capabilities.7.html


I had a quick chat with Justin Cormack via the Docker community slack and he pointed out that:
> if you read the source code for NVME_IOCTL_ADMIN_CMD it requires CAP_SYS_ADMIN, so there is nothing you can do except grant that.
> it calls nvme_user_cmd which s the check in https://elixir.bootlin.com/linux/v4.4/source/drivers/nvme/host/pci.c#L1882
> the call is https://elixir.bootlin.com/linux/v4.4/source/drivers/nvme/host/pci.c#L1940

So it looks like `--cap-add SYS_ADMIN` is required for NVMe drives, but `--cap-add SYS_RAWIO` is enough for SATA/SCSI drives. 

If you have a mix of both SATA/NVMe, you must include both flags:


```
--cap-add SYS_ADMIN \
--cap-add SYS_RAWIO \
```

---

~~I tried to do some googling (and spelunking in the Linux kernel) but I couldn't figure out which capability allows access to `NVME_IOCTL_ADMIN_CMD`. The only one's that even look they're vaguely related is `CAP_SYS_RESOURCE`, which docker provides via `--cap-add SYS_RESOURCE`.~~

~~Unfortunately I don't have a NVMe drive myself, but if I was going to test this (and `SYS_RESOURCE` didn't work), I would do the following:~~

- ~~Run Scrutiny with all extended capabilities~~
    - ~~excluding `SYS_ADMIN`, since we know that works~~
- ~~Verify that it works correctly~~
- ~~Start removing capabilities one by one~~
    - ~~make sure we do not remove `SYS_RAWIO`~~
    - ~~watch for the `NVME_IOCTL_ADMIN_CMD` error when running `smartctl`. The last capability we removed is the one we need.~~
- ~~Re-add the capability to ensure that `NVME_IOCTL_ADMIN_CMD` disappears.~~

~~It could be either super quick (`smartctl` fails without removing any capabilities, meaning it requires `SYS_ADMIN` to run with NVMe drives), or it could be incredibly tedious. I totally understand if you're not up for it.~~

**Comment by mrhotio** [comment]
fyi, now that it works....I only need the following stuff to get it working

```
--cap-add SYS_ADMIN
--device /dev/nvme0
```

so no `-v /run/udev:/run/udev:ro`, or is that for some upcoming feature?

**Comment by AnalogJ** [comment]
Yeah, `-v /run/udev` is used to retrieve metadata for filtering virtual devices & as a fallback method to lookup WWN device identifiers. 

Though, if you don't have it, Scrutiny may use your serial number as a device identifier instead.

**Comment by parkerlreed** [comment]
Tried with NVME and the web page shows No Devices

```
[parker@stealth ~]$ docker run -it --rm -p 8080:8080 -v /run/udev:/run/udev:ro --cap-add SYS_ADMIN --device=/dev/nvme0 --name scrutiny analogj/scrutiny
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
starting jobber/cron
starting scrutiny
[services.d] done.
2020/09/28 20:36:06 No configuration file found at /scrutiny/config/scrutiny.yaml. Skipping

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                             dev-0.2.1

Start the scrutiny server
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

Trying to connect to database stored: /scrutiny/config/scrutiny.db
[GIN-debug] GET    /api/health               --> github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup.func1 (5 handlers)
[GIN-debug] POST   /api/health/notify        --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.SendTestNotification (5 handlers)
[GIN-debug] POST   /api/devices/register     --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.RegisterDevices (5 handlers)
[GIN-debug] GET    /api/summary              --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.GetDevicesSummary (5 handlers)
[GIN-debug] POST   /api/device/:wwn/smart    --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.UploadDeviceMetrics (5 handlers)
[GIN-debug] POST   /api/device/:wwn/selftest --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.UploadDeviceSelfTests (5 handlers)
[GIN-debug] GET    /api/device/:wwn/details  --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.GetDeviceDetails (5 handlers)
[GIN-debug] GET    /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] HEAD   /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] GET    /                         --> github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup.func2 (5 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:8080
INFO[0006] 172.17.0.1 - 54a98d17b700 [28/Sep/2020:20:36:13 +0000] "GET /" 302 27 "" "Mozilla/5.0 (X11; CrOS armv7l 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36" (1ms)  clientIP=172.17.0.1 hostname=54a98d17b700 latency=1 method=GET path=/ referer= respLength=27 statusCode=302 userAgent="Mozilla/5.0 (X11; CrOS armv7l 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36"
INFO[0006] 172.17.0.1 - 54a98d17b700 [28/Sep/2020:20:36:13 +0000] "GET /api/summary" 200 26 "http://localhost:8080/web/" "Mozilla/5.0 (X11; CrOS armv7l 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36" (1ms)  clientIP=172.17.0.1 hostname=54a98d17b700 latency=1 method=GET path=/api/summary referer="http://localhost:8080/web/" respLength=26 statusCode=200 userAgent="Mozilla/5.0 (X11; CrOS armv7l 13099.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.110 Safari/537.36"
```

**Comment by derekcentrico** [comment]
This workaround isn't working for me at all.  Is this still valid?  Any changes?

My docker:
```
  scrutinyanalogj:
    ports:
      - '86:80'
      - '8886:8080'
    volumes:
#      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/home/docker/scrutinyanalogj:/opt/scrutiny/config'
      - '/home/docker/influxdb2:/opt/scrutiny/influxdb'
      - '/run/udev:/run/udev:ro'
    restart: always
    logging:
      options:
        max-size: 1g
    container_name: scrutinyanalogj
    environment:
      - PUID=1000
      - PGID=996
      - TZ=America/New_York
    devices:
      - '/dev/nvme0n1p1:/dev/nvme0n1p1'
      - '/dev/nvme1n1p1:/dev/nvme1n1p1'
      - '/dev/nvme2n1p1:/dev/nvme2n1p1'
      - '/dev/sda:/dev/sda'
      - '/dev/sdb:/dev/sdb'
      - '/dev/sdc:/dev/sdc'
      - '/dev/sdd:/dev/sdd'
      - '/dev/sde:/dev/sde'
      - '/dev/sdf:/dev/sdf'
      - '/dev/sdg:/dev/sdg'
      - '/dev/sdh:/dev/sdh'
      - '/dev/sdi:/dev/sdi'
      - '/dev/sdj:/dev/sdj'
      - '/dev/sdk:/dev/sdk'
      - '/dev/sdl:/dev/sdl'
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    image: ghcr.io/analogj/scrutiny:master-omnibus
    networks:
      vpnsys_net:
        ipv4_address: '172.22.0.109'
```
