### ISSUE TITLE
[BUG] Crashes on boot

### ISSUE THREAD

**Issue by ViRb3** [AnalogJ/scrutiny#281]
**Describe the bug**
After updating to 0.4.9-omnibus, scrutiny can no longer boot - it always crashes as it starts up.

**System**
- Ubuntu 22.04 arm64
- Docker Compose
```yaml
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.4.9-omnibus
    privileged: true
    volumes:
      - /run/udev:/run/udev:ro
      - /dev:/dev
      - scrutiny-config:/opt/scrutiny/config
      - scrutiny-db:/opt/scrutiny/influxdb
    networks:
      - scrutiny-nginx
```

**Log Files**
```
 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                             dev-0.4.9

Start the scrutiny server
time="2022-06-05T18:02:42Z" level=info msg="Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n"
panic: failed to check influxdb setup status - Get "http://localhost:8086/api/v2/setup": dial tcp: lookup localhost: device or resource busy

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x103a6c0, 0x4000010ce8}, {0x1043620, 0x4000430070})
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xd4
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0x400042a630, {0x1043620, 0x4000430070})
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:27 +0x90
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0x400042a630)
	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:105 +0x530
main.main.func2(0x40003ffcc0)
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x288
github.com/urfave/cli/v2.(*Command).Run(0x400042e120, 0x40003ffb40)
	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x648
github.com/urfave/cli/v2.(*App).RunContext(0x40002fc480, {0x1026870, 0x400003a028}, {0x4000032060, 0x2, 0x2})
	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x840
github.com/urfave/cli/v2.(*App).Run(...)
	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
main.main()
	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x73c
```

**Comment by cmdpedro** [comment]
I have the same issue. The panic is also about a failed check of influxdb status, although I have a slightly different error message:

```
scrutiny         | / __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
scrutiny         | \__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
scrutiny         | (___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
scrutiny         | github.com/AnalogJ/scrutiny                             dev-0.4.9
scrutiny         | Start the scrutiny server
scrutiny         | time="2022-06-06T00:46:23+01:00" level=info msg="Trying to connect to scrutiny sqlite db: \n"
scrutiny         | time="2022-06-06T00:46:23+01:00" level=info msg="Successfully connected to scrutiny sqlite db: \n"
scrutiny         | panic: failed to check influxdb setup status - parse "://:": missing protocol scheme
scrutiny         | goroutine 1 [running]:
scrutiny         | github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x10b2100, 0xc000010ce8}, {0x10bb7d0, 0xc000423f10})
scrutiny         | 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:14 +0xa5
scrutiny         | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000420600, {0x10bb7d0, 0xc000423f10})
scrutiny         | 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:27 +0xb4
scrutiny         | github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000420600)
scrutiny         | 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:105 +0x46b
scrutiny         | main.main.func2(0xc000173bc0)
scrutiny         | 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x1f7
scrutiny         | github.com/urfave/cli/v2.(*Command).Run(0xc000426240, 0xc000173a40)
scrutiny         | 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x64a
scrutiny         | github.com/urfave/cli/v2.(*App).RunContext(0xc000280600, {0x109c3d0, 0xc000036080}, {0xc000032040, 0x2, 0x2})
scrutiny         | 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0x926
scrutiny         | github.com/urfave/cli/v2.(*App).Run(...)
scrutiny         | 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
scrutiny         | main.main()
scrutiny         | 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x679
```

**Comment by AnalogJ** [comment]
can you try running without `--privileged` and `-v /dev:/dev`?
Instead just start the container with `--device` flags?

**Comment by ViRb3** [comment]
Just tried, exactly same error:

```yaml
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:v0.4.9-omnibus
    volumes:
      - /run/udev:/run/udev:ro
      - scrutiny-config:/opt/scrutiny/config
      - scrutiny-db:/opt/scrutiny/influxdb
    networks:
      - scrutiny-nginx
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
```
