### ISSUE TITLE
[BUG] Web interface only showing the last hard drive of my array

### ISSUE THREAD

**Issue by jeroengui** [AnalogJ/scrutiny#285]
**Describe the bug**
When using cciss hard drives in collector.yaml I only see the last one in the web application.
I also tried it with only the first 4 devices in the collector.yaml file and then also only the last (the 4th hard drive) showed up.
Contents of my collector.yaml file:
```
version: 1
devices:
  - device: /dev/sda
    type:
      - cciss,0
      - cciss,1
      - cciss,2
      - cciss,3
      - cciss,4
      - cciss,5
      - cciss,6
      - cciss,7
```

**Expected behavior**
It should show all hard drives listed in collector.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/52084809/172192429-5b9fad09-d39e-459d-b740-490cf493483f.png)

**Log Files**
[collector.log](https://github.com/AnalogJ/scrutiny/files/8845521/collector.log)
[web.log](https://github.com/AnalogJ/scrutiny/files/8845524/web.log)
