### ISSUE TITLE
[FEAT] Notify on Critical Only

### ISSUE THREAD

**Issue by jimmybrancaccio** [AnalogJ/scrutiny#300]
**Is your feature request related to a problem? Please describe.**

I only have 3 servers added to my Scrutiny instance with a collective 22 drives and I get at least 20 emails per day about various drives in failing states. It's been about 2 weeks since I've had Scrutiny running but I'm at notification overload and at this point I just delete all the emails.

**Describe the solution you'd like**

To assist with this would it be possible to implement a feature that sends notification on when a critical measurement is failing? For example just notify on these measurements:

<img width="1363" alt="scrutiny" src="https://user-images.githubusercontent.com/405585/173467994-ed1033cd-306f-453a-b023-e82a0324bd45.png">

**Additional context**

N/A

**Comment by AnalogJ** [comment]
oh this is definitely a good quality of life feature. I'll definitely add support for filtering notification triggers.

**Comment by AnalogJ** [comment]
I'm playing around with a couple of different config file syntax options, but I think something like this might make sense:

```yaml
notify:
  urls:
    - "discord://token@channel"
    - "telegram://token@telegram?channels=channel-1[,channel-2,...]"
    - "pushover://shoutrrr:apiToken@userKey/?priority=1&devices=device1[,device2, ...]"
    ...
  filter_attributes: 'all' # options: 'all' or  'critical'
  level: 'fail' # options: 'fail', 'fail_scrutiny', 'fail_smart'
  
```

@jimmybrancaccio @gofaster What do you think?
