### ISSUE TITLE
[BUG] Data is not written to DB

### ISSUE THREAD

**Issue by NemesisRE** [AnalogJ/scrutiny#305]
**Describe the bug**
Data is not written to DB

**Expected behavior**
Data is written to DB

**Screenshots**

**Log Files**
```
time="2022-06-16T01:38:46Z" level=info msg="Collecting smartctl results for sdi\n" type=metrics
time="2022-06-16T01:38:46Z" level=info msg="Executing command: smartctl --xall --json /dev/sdi" type=metrics
time="2022-06-16T01:38:46Z" level=info msg="Publishing smartctl results for 0x5001b444a7f84b80\n" type=metrics
time="2022-06-16T01:38:46Z" level=error msg="An error occurred while saving smartctl metrics unprocessable entity: failure writing points to database: partial write: points beyond retention policy dropped=1"
time="2022-06-16T01:38:46Z" level=error msg="127.0.0.1 - scrutiny [16/Jun/2022:01:38:46 +0000] \"POST /api/device/0x5001b444a7f84b80/smart\" 500 17 \"\" \"Go-http-client/1.1\" (29ms)" clientIP=127.0.0.1 hostname=scrutiny latency=29 method=POST path=/api/device/0x5001b444a7f84b80/smart referer= respLength=17 statusCode=500 userAgent=Go-http-client/1.1
```
```
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    hostname: scrutiny
    cap_add:
      - SYS_ADMIN
    volumes:
      - /run/udev:/run/udev:ro
      - /mnt/DATA/Scrutiny/config:/opt/scrutiny/config
      - /mnt/DATA/Scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/nvme0n1:/dev/nvme0n1
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/sdj:/dev/sdj
      - /dev/sdk:/dev/sdk
      - /dev/sdl:/dev/sdl
    networks:
      MediaStation:
        ipv4_address: XXX.XXX.XXX.XXX
    restart: unless-stopped
```
```
❯ docker info
Client:
  Debug Mode: false
  Plugins:
    buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
    compose: Docker Compose (Docker Inc., v2.2.0)

Server:
  Containers: 74
    Running: 74
    Paused: 0
  Images: 101
  Server Version: 20.10.17
    Supports d_type: true
    userxattr: false
  Logging Driver: loki
  Cgroup Version: 2
  Plugins:
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
  Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
  Default Runtime: nvidia
  containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  runc version: v1.1.2-0-ga916309
  Security Options:
    apparmor
    seccomp
      Profile: default
    cgroupns
  Kernel Version: 5.15.0-37-generic
  Operating System: Ubuntu 22.04 LTS
  OSType: linux
  Architecture: x86_64
  CPUs: 12
  Total Memory: 31.27GiB
  Name: HOSTNAME
  Docker Root Dir: /mnt/DATA/.docker
  Debug Mode: false
  Username: USERNAME
  Registry: https://index.docker.io/v1/
  Labels:
  Insecure Registries:
  Live Restore Enabled: false
  ```
