### ISSUE TITLE
Whether support QNAP NAS

### ISSUE THREAD

**Issue by 870561859** [AnalogJ/scrutiny#326]
Whether support QNAP NAS

**Comment by AnalogJ** [comment]
QNAP is supported

**Comment by ayancey** [comment]
For anyone else on QNAP, here's my experience:

`Entware-ng` is a dead-end, because the version of smartmontools is so old. Don't be like me going down such a dumb rabbit hole. [This](https://github.com/Entware/Entware/wiki/Install-on-QNAP-NAS) will probably work for you just fine, but I was able to run the generic x86 install script in bash and that also worked.

For the rest of the install, the manual guide mostly worked for me. Here's my config:

```yaml
version: 1

host:
  id: "qnap"

# Auto config works for me for NVMe SSDs, but not drives.
devices:
  - device: /dev/sda
    type: sat
  - device: /dev/sdb
    type: sat
  - device: /dev/sdc
    type: sat
  - device: /dev/sdd
    type: sat
  - device: /dev/sde
    type: sat
  - device: /dev/sdf
    type: sat
  - device: /dev/sdg
    type: sat
  - device: /dev/sdh
    type: sat
  - device: /dev/sdi
    type: sat
  - device: /dev/sdj
    type: sat
  - device: /dev/sdk
    type: sat
  - device: /dev/sdl
    type: sat

# Not sure if path would be correct on QNAP QTS
commands:
  metrics_smartctl_bin: '/opt/sbin/smartctl'
```

I wrote a [blog post](https://alexyancey.com/installing-scrutiny-on-qnap-qts-nas/) which might help you further, but I'm not confident enough to write a guide. The devil is really in the details here, but I just happened to get it working on my TS-1683XU-RP (runs x86) running QTS 5.2.3.3006.
