### ISSUE TITLE
Can't start Scrutiny

### ISSUE THREAD

**Issue by Nabukodonosor** [AnalogJ/scrutiny#331]
Hey guys. I installed Scrutiny months ago, and it worked fine. But now, I wanted to check something, tried to start it and it doesn't start:

`Unable to connect

Firefox can’t establish a connection to the server at 192.168.0.111:8080.`

This is my docker compose:

```
---
version: "2.1"
services:
  scrutiny:
    image: lscr.io/linuxserver/scrutiny:latest
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    privileged: true
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Belgrade
      - SCRUTINY_API_ENDPOINT=http://localhost:8080 #DO NOT CHANGE THIS LINE
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /MainPool/Documents/Containers/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
    restart: unless-stopped
    
    
#Run this command in Container Console to update data: 
#   scrutiny-collector-metrics run
```

Tried different browsers, no luck. Tried to completelly uninstall it and install again, the issue remained. Any ideas?

The only error in the logs I see is this:
panic: failed to check influxdb setup status - parse "://:": missing protocol scheme
