### ISSUE TITLE
[BUG] scrutiny api not ready

### ISSUE THREAD

**Issue by ovizii** [AnalogJ/scrutiny#358]
**Describe the bug**
Cannot access scrutiny web GUI. This seems to have happened recently after an automatic update of scrutiny via watchtower. 
I found a few issues from around June this year but none seemed exactly the same so I opened a fresh issue.

**Expected behavior**
I'd expect to be able to access the web GUI


**Log Files**
```
scrutiny  | ts=2022-08-12T08:55:46.034541Z lvl=info msg="Starting retention policy enforcement service" log_id=0cGK6a1G000 service=retention check_interval=30m                                                                                                                                           
scrutiny  | ts=2022-08-12T08:55:46.034571Z lvl=info msg="Starting precreation service" log_id=0cGK6a1G000 service=shard-precreation check_interval=10m advance_period=30m                                                                                                                                 
scrutiny  | ts=2022-08-12T08:55:46.036521Z lvl=info msg="Starting query controller" log_id=0cGK6a1G000 service=storage-reads concurrency_quota=1024 initial_memory_bytes_quota_per_query=9223372036854775807 memory_bytes_quota_per_query=9223372036854775807 max_memory_bytes=0 queue_size=1024          
scrutiny  | ts=2022-08-12T08:55:46.105302Z lvl=info msg="Configuring InfluxQL statement executor (zeros indicate unlimited)." log_id=0cGK6a1G000 max_select_point=0 max_select_series=0 max_select_buckets=0                                                                                              
scrutiny  | ts=2022-08-12T08:55:46.175684Z lvl=info msg=Listening log_id=0cGK6a1G000 service=tcp-listener transport=http addr=:8086 port=8086        
scrutiny  | scrutiny api not ready                                                                                                                   
scrutiny  | starting scrutiny                                                                                                                        
scrutiny  | 2022/08/12 10:55:50 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml                                                       
scrutiny  | waiting for influxdb                                                                                                                     
scrutiny  | starting scrutiny                                                                                                                        
scrutiny  | 2022/08/12 10:55:50 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml                                                       
scrutiny  | waiting for influxdb                                                                                                                     
scrutiny  | starting scrutiny                                                                                                                        
scrutiny  | 2022/08/12 10:55:51 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml                                                       
scrutiny  | waiting for influxdb                                                                                                                     
scrutiny  | starting scrutiny                                                                                                                        
scrutiny  | 2022/08/12 10:55:52 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml    
```
I cut the logs off here as the last few lines simply keep repeating.

Please also provide the output of `docker info`

```
docker info                                                                                                         
Client:                                                                                                                                              
 Context:    default                                                                                                                                 
 Debug Mode: false                                                                                                                                   
 Plugins:                                                                                                                                            
  app: Docker App (Docker Inc., v0.9.1-beta3)                                                                                                        
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)                                                                                                 
  compose: Docker Compose (Docker Inc., v2.6.0)                                                                                                      
  scan: Docker Scan (Docker Inc., v0.17.0)                                                                                                           
                                                                                                                                                     
Server:                                                                                                                                              
 Containers: 46                                                                                                                                      
  Running: 46                                                                                                                                        
  Paused: 0                                                                                                                                          
  Stopped: 0                                                                                                                                         
 Images: 53                                                                                                                                          
 Server Version: 20.10.17                                                                                                                            
 Storage Driver: zfs                                                                                                                                 
  Zpool: rpool                                                                                                                                       
  Zpool Health: ONLINE                                                                                                                               
  Parent Dataset: rpool/docker                                                                                                                       
  Space Used By Parent: 19052621824                                                                                                                  
  Space Available: 717979443200                                                                                                                      
  Parent Quota: no                                                                                                                                   
  Compression: on                                                                                                                                    
 Logging Driver: json-file                                                                                                                           
 Cgroup Driver: systemd                                                                                                                              
 Cgroup Version: 2                                                                                                                                   
 Plugins:                                                                                                                                            
  Volume: local                                                                                                                                      
  Network: bridge host ipvlan macvlan null overlay                                                                                                   
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog                                                                
 Swarm: inactive                                                                                                                                     
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc                                                                                 
 Default Runtime: runc                                                                                                                               
 Init Binary: docker-init                                                                                                                            
 containerd version: 0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb                                                                                        
 runc version: v1.1.3-0-g6724737                                                                                                                     
 init version: de40ad0                                                                                                                               
 Security Options:                                                                                                                                   
  apparmor                                                                                                                                           
  seccomp                                                                                                                                            
   Profile: default                                                                                                                                  
  cgroupns                                                                                                                                           
 Kernel Version: 5.15.39-1-pve                                                                                                                       
 Operating System: Debian GNU/Linux 11 (bullseye)                                                                                                    
 OSType: linux                                                                                                                                       
 Architecture: x86_64                                                                                                                                
 CPUs: 12                                                                                                                                            
 Total Memory: 125.7GiB                                                                                                                              
 Name: nas                                                                                                                                           
 ID: 7DNV:NFYT:censored:JOJB                                                                                     
 Docker Root Dir: /var/lib/docker                                                                                                                    
 Debug Mode: false                                                                                                                                   
 Username: ovizii                                                                                                                                    
 Registry: https://index.docker.io/v1/                                                                                                               
 Labels:                                                                                                                                             
 Experimental: false                                                                                                                                 
 Insecure Registries:                                                                                                                                
  127.0.0.0/8                                                                                                                                        
 Live Restore Enabled: false                                                                                                                         
 Default Address Pools:                                                                                                                              
   Base: 172.16.0.0/12, Size: 24                                                                                                                     
                                                                                                                                                     
WARNING: bridge-nf-call-iptables is disabled                                                                                                         
WARNING: bridge-nf-call-ip6tables is disabled                                       
```

docker-compose.yml

```
version: "3.8"                                                                                                                                       
                                                                                                                                                     
# switched to the official one since linuxserver broke                                                                                               
# https://github.com/AnalogJ/scrutiny/blob/master/docker/example.omnibus.docker-compose.yml                                                          
                                                                                                                                                     
services:                                                                                                                                            
  scrutiny:                                                                                                                                          
    image: ghcr.io/analogj/scrutiny:master-omnibus                                                                                                   
    container_name: scrutiny                                                                                                                         
    hostname: scrutiny                                                                                                                               
    cap_add:                                                                                                                                         
      - SYS_RAWIO                                                                                                                                    
      - SYS_ADMIN                                                                                                                                    
    environment:                                                                                                                                     
      - PUID=1000                                                                                                                                    
      - PGID=1000                                                                                                                                    
      - TZ=Europe/Berlin                                                                                                                             
      - COLLECTOR_API_ENDPOINT=http://localhost:8080                                                                                                 
    volumes:                                                                                                                                         
      - ./config:/opt/scrutiny/config                                                                                                                
      - ./influxdb:/opt/scrutiny/influxdb                                                                                                            
      - /run/udev:/run/udev:ro                                                                                                                       
    devices:                                                                                                                                         
      - /dev/sda:/dev/sda                                                                                                                            
      - /dev/sdb:/dev/sdb                                                                                                                            
      - /dev/sdc:/dev/sdc                                                                                                                            
      - /dev/sdd:/dev/sdd                                                                                                                            
      - /dev/sde:/dev/sde                                                                                                                            
      - /dev/sdf:/dev/sdf                                                                                                                            
      - /dev/nvme0:/dev/nvme0                                                                                                                        
      - /dev/nvme1:/dev/nvme1                                                                                                                        
    restart: "no"                                                                                                                                    
    networks:                                                                                                                                        
      - scrutiny                                                                                                                                     
      - traefik                                                                                                                                      
    labels:                                                                                                                                          
      - "traefik.enable=true"                                                                                                                        
      - "traefik.docker.network=traefik"                                                                                                             
      - "traefik.http.routers.scrutiny.tls=true"                                                                                                     
      - "traefik.http.routers.scrutiny.entrypoints=https"                                                                                            
      - "traefik.http.routers.scrutiny.rule=Host(`scrutiny.domain.tld`)"                                                                                 
      - "traefik.http.routers.scrutiny.middlewares=secHeaders@file,localIPsOnly@file,authentik@docker"                                               
      - "traefik.http.routers.scrutiny.service=scrutiny"                                                                                             
      - "traefik.http.services.scrutiny.loadbalancer.server.port=8080"                                                                               
                                                                                                                                                     
                                                                                                                                                     
networks:                                                                                                                                            
    scrutiny:                                                                                                                                        
      external: true                                                                                                                                 
      name: scrutiny                                                                                                                                 
    traefik:                                                                                                                                         
      external: true                                                                                                                                 
      name: traefik 
```

scrutiny.yaml

```
version: 1                                                                                                                                           
                                                                                                                                                     
web:                                                                                                                                                 
  listen:                                                                                                                                            
    port: 8080                                                                                                                                       
    host: 0.0.0.0                                                                                                                                    
  database:                                                                                                                                                                                                                                               
    location: /opt/scrutiny/config/scrutiny.db                                                                                                       
  src:                                                                                                                                               
    frontend:                                                                                                                                        
      path: /opt/scrutiny/web       
  influxdb:                                                                                                                                          
    host: 0.0.0.0                                                                                                                                    
    port: 8086                                                                                                                                       
    retention_policy: true                                                                                                                           
                                                                                                                                                     
disks:                                                                                                                                               
  include:                                                                                                                                           
    - /dev/sda                                                                                                                                       
    - /dev/sdb                                                                                                                                       
    - /dev/sdc                                                                                                                                       
    - /dev/sdd                                                                                                                                       
    - /dev/sde                                                                                                                                       
    - /dev/sdf                                                                                                                                       
    - /dev/nvme0                                                                                                                                     
    - /dev/nvme1                                                                                                                                     
  exclude:                                                                                                                                           
                                                                                                                                                     
notify:                                                                                                                                              
  level: 'warn' 
  urls: 
    - "pushbullet://mysecret/me@email.tld"   
```
