### ISSUE TITLE
[BUG] Permissions of Influxdb folder do not follow PUID/PGID set in the docker-compose file

### ISSUE THREAD

**Issue by garret** [AnalogJ/scrutiny#362]
I ran scrutiny with such docker-compose scheme on my raspberry pi 4b (4GB): 

```
    scrutiny:
        cap_add:
            - SYS_RAWIO
        ports:
            - 8123:8080
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
        volumes:
            - /run/udev:/run/udev:ro
            - ${CONFIG_FOLDER}/scrutiny/config:/opt/scrutiny/config
            - ${CONFIG_FOLDER}/scrutiny/influxdb:/opt/scrutiny/influxdb
        devices:
            - /dev/sdb
        container_name: scrutiny
        restart: unless-stopped
        image: ghcr.io/analogj/scrutiny:master-omnibus
```

Since it was introduced the _influxdb_ database I now encounter the issue that the `/opt/scrutiny/influxdb` folder is not locally saved after my `PUID` and `PGID` settings (set in an `.env` file next to my docker-compose file). That is not the case for the `/opt/scrutiny/config` folder which instead respects the `PUID` and `PGID` settings. 

I tried adding `user: ${PUID}:${PGID}` in the docker-compose but in that way scrutiny does not event start. 

Do you know how to solve such issue?
