### ISSUE TITLE
waiting for influxdb

### ISSUE THREAD

**Issue by PriamX** [AnalogJ/scrutiny#365]
Using the **omnibus** docker container, repeatedly getting the following error in the log file.

```
2022/08/30 14:24:58 Loading configuration file: /opt/scrutiny/config/scrutiny.yaml
waiting for influxdb
```

Influx seems to start fine, but not scrutiny.

`Docker version 20.10.17, build 100c701`

I assume scrutiny is not connecting to influxdb, is there some initial configuration of influxdb that I need to do? When pointing my web browser at port 8086 (influx) it's prompting me to set up an initial user.

I'm using the following command (note the port mapping on the host side to avoid an existing tomcat conflict 8080->8084):

```
docker run -d \
  --name=scrutiny \
  --cap-add=SYS_RAWIO \
  --cap-add=SYS_ADMIN `#optional` \
  -e PUID=981 \
  -e PGID=100 \
  -e TZ=America/Denver \
  -p 8084:8080 \
  -p 8086:8086 \
  --network="mynet" \
  -v /media/docker/appdata/scrutiny:/opt/scrutiny/config \
  -v /media/docker/appdata/influxdb2:/opt/scrutiny/influxdb \
  -v /run/udev:/run/udev:ro \
  --device /dev/sda:/dev/sda \
  --device /dev/sdb:/dev/sdb \
  --device /dev/sdc:/dev/sdc \
  --device /dev/sdd:/dev/sdd \
  --device /dev/nvme0n1:/dev/nvme0n1 \
  --device /dev/nvme1n1:/dev/nvme1n1 \
  --device /dev/sr0:/dev/sr0 \
  --device /dev/bus:/dev/bus \
  --restart unless-stopped \
  ghcr.io/analogj/scrutiny:master-omnibus
```

**Comment by PriamX** [comment]
So...

Logging into the docker container, and viewing the `/opt/scrutiny/config/scrutiny.yaml` file shows the following:

```
[snip]
web:
  listen:
    port: 8080
    host: 0.0.0.0
  database:
    # can also set absolute path here
    location: /config/scrutiny.db
  src:
    frontend:
      path: /app/scrutiny-web
[snip]
```

I'm new to this scrutiny, but thinking, that can't be right, there is no `/config` nor `/app` directory in the docker container that was deployed. I'm thinking this scrutiny.yaml is all wrong?
