### ISSUE TITLE
Trouble getting drives behind megaraid to show

### ISSUE THREAD

**Issue by PriamX** [AnalogJ/scrutiny#366]
I have 10 drives behind an LSI/Avago/Broadcom MegaRAID 9361-16i adapter.

```------------------------------------------------------------------------------------
EID:Slt DID State DG       Size Intf Med SED PI SeSz Model                  Sp Type
------------------------------------------------------------------------------------
252:0    63 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:1    64 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:2    62 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:3    61 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:4    67 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:5    68 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:6    66 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:7    65 Onln   0   7.276 TB SATA HDD N   N  512B WDC WD8003FFBX-68B9AN0 U  -
252:8    70 Onln   1 185.781 GB SAS  SSD Y   N  512B H1SMR324 CLAR200       U  -
252:9    69 Onln   1 185.781 GB SAS  SSD Y   N  512B H1SMR324 CLAR200       U  -
------------------------------------------------------------------------------------
```

On the host, a `smartclt --scan` shows them just fine, the OS (Fedora 35) uses the RAID as `/dev/sdc`:

`smartctl 7.3 2022-02-28 r5338 [x86_64-linux-5.19.4-100.fc35.x86_64] (local build)`

```
[root@myserv ~]# smartctl --scan
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/sdc -d scsi # /dev/sdc, SCSI device
/dev/bus/13 -d megaraid,61 # /dev/bus/13 [megaraid_disk_61], SCSI device
/dev/bus/13 -d megaraid,62 # /dev/bus/13 [megaraid_disk_62], SCSI device
/dev/bus/13 -d megaraid,63 # /dev/bus/13 [megaraid_disk_63], SCSI device
/dev/bus/13 -d megaraid,64 # /dev/bus/13 [megaraid_disk_64], SCSI device
/dev/bus/13 -d megaraid,65 # /dev/bus/13 [megaraid_disk_65], SCSI device
/dev/bus/13 -d megaraid,66 # /dev/bus/13 [megaraid_disk_66], SCSI device
/dev/bus/13 -d megaraid,67 # /dev/bus/13 [megaraid_disk_67], SCSI device
/dev/bus/13 -d megaraid,68 # /dev/bus/13 [megaraid_disk_68], SCSI device
/dev/bus/13 -d megaraid,69 # /dev/bus/13 [megaraid_disk_69], SCSI device
/dev/bus/13 -d megaraid,70 # /dev/bus/13 [megaraid_disk_70], SCSI device
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device
/dev/nvme1 -d nvme # /dev/nvme1, NVMe device
[root@myserv ~]#
```

In the docker container, they do not appear (I noticed the smartctl version is slightly older):

`smartctl 7.2 2020-12-30 r5155 [x86_64-linux-5.19.4-100.fc35.x86_64] (local build)`

```
[root@myserv ~]# docker exec -it scrutiny /bin/bash
root@0521a150d7f2:/opt/scrutiny# smartctl --scan
/dev/sda -d scsi # /dev/sda, SCSI device
/dev/sdb -d scsi # /dev/sdb, SCSI device
/dev/sdc -d scsi # /dev/sdc, SCSI device
/dev/nvme0 -d nvme # /dev/nvme0, NVMe device
/dev/nvme1 -d nvme # /dev/nvme1, NVMe device
root@0521a150d7f2:/opt/scrutiny#
```

I have mapped `/dev/bus` through to the docker container, here's the docker command I'm using to deploy scrutiny:

```
docker run -d \
  --name=scrutiny \
  --cap-add=SYS_RAWIO \
  --cap-add=SYS_ADMIN `#optional` \
  -e TZ=America/Denver \
  -p 8084:8080 \
  -p 8086:8086 \
  --network="mynet" \
  -v /media/docker/appdata/scrutiny:/opt/scrutiny/config \
  -v /media/docker/appdata/influxdb2:/opt/scrutiny/influxdb \
  -v /run/udev:/run/udev:ro \
  --device /dev/sda:/dev/sda \
  --device /dev/sdb:/dev/sdb \
  --device /dev/sdc:/dev/sdc \
  --device /dev/sdd:/dev/sdd \
  --device /dev/nvme0:/dev/nvme0 \
  --device /dev/nvme1:/dev/nvme1 \
  --device /dev/sr0:/dev/sr0 \
  --device /dev/bus:/dev/bus \
  --restart unless-stopped \
  ghcr.io/analogj/scrutiny:master-omnibus
```

Here's the devices section from the `collector.yaml` I'm using:

```
devices:

   - device: /dev/sda
     type: 'ata'

   - device: /dev/sdb
     type: 'ata'

   - device: /dev/bus/13
     type:
       - megaraid,61
       - megaraid,62
       - megaraid,63
       - megaraid,64
       - megaraid,65
       - megaraid,66
       - megaraid,67
       - megaraid,68
       - megaraid,69
       - megaraid,70

   - device: /dev/sdd
     type:
       - jmb39x-q,0
       - jmb39x-q,1

   - device: /dev/nvme0
     type: 'nvme'

   - device: /dev/nvme1
     type: 'nvme'

   - device: /dev/sr0
     type: 'ata'
```

Here's the dashboard:

![image](https://user-images.githubusercontent.com/43935458/187578390-97cecc15-a954-46e6-833f-2137ea3cc677.png)

Has anyone got a MegaRAID to work with Scrutiny, if so, are there any tricks I'm missing?

Thanks!
