### ISSUE TITLE
[BUG] Scrutiny on docker remembers forever my first config even by deleting the entire config and influxdb folder

### ISSUE THREAD

**Issue by garret** [AnalogJ/scrutiny#376]
There is this behavior I cannot explain where even by stopping scrutiny, deleting my local `${CONFIG_FOLDER}/scrutiny` folder and restarting the container, Scrutiny still starts like such folder was never deleted. Therefore, all influxdb data are there and also if I access through the container console to `/opt/scrutiny/config/scrutiny.yaml` I can still see the old `${CONFIG_FOLDER}/scrutiny/config/scrutiny.yaml` which was deleted. 

This is my docker-compose: 

```
    scrutiny:
        cap_add:
            - SYS_RAWIO
        ports:
            - 8085:8080
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TIMEZONE}
        volumes:
            - /run/udev:/run/udev:ro
            - ${CONFIG_FOLDER}/scrutiny/config:/opt/scrutiny/config
            - ${CONFIG_FOLDER}/scrutiny/influxdb:/opt/scrutiny/influxdb
        devices:
            - /dev/sda
        container_name: scrutiny
        restart: unless-stopped
        image: ghcr.io/analogj/scrutiny:master-omnibus
```

Can you explain such behavior? 

I checked through portainer and there are no random volumes associated with scrutiny container.
