### ISSUE TITLE
[FEAT] Regarding the manual installation/running

### ISSUE THREAD

**Issue by parkerlreed** [AnalogJ/scrutiny#47]
Coming from the Reddit post, I'm trying to run the binaries manually on my system without the use of docker.

When I try starting the web server it looks for a non-existent database. Do I need to create that manually or is there a command I am missing?

```
[parker@stealth ~]$ ./scrutiny-web-linux-amd64 start 
2020/09/28 17:02:02 No configuration file found at /scrutiny/config/scrutiny.yaml. Skipping

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.amd64-0.2.1

Start the scrutiny server
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

Trying to connect to database stored: /scrutiny/config/scrutiny.db
panic: Failed to connect to database!

goroutine 1 [running]:
github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.DatabaseMiddleware(0xeac900, 0xc00033e058, 0xeb1d60, 0xc00038c9a0, 0xeadc80)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/sqlite3.go:18 +0x48c
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc00033b0b0, 0xeb1d60, 0xc00038c9a0, 0x0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:23 +0xcf
github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc00033b0b0, 0x0, 0x0)
        /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:80 +0x1cb
main.main.func2(0xc000344ec0, 0x4, 0x6)
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:112 +0x198
github.com/urfave/cli/v2.(*Command).Run(0xc000369c20, 0xc000344d40, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4b9
github.com/urfave/cli/v2.(*App).RunContext(0xc00039e000, 0xea04c0, 0xc0000a6010, 0xc00009e020, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x790
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:137 +0x703
```

**Comment by parkerlreed** [comment]
Ok so the server creates the database if running as root. I will try customizing the config to a user location to see if that works.

**Comment by parkerlreed** [comment]
Ok yes after creating a custom user path and config file it does indeed work

```
[parker@stealth ~]$ ./scrutiny-web-linux-amd64 start --config ~/.config/scrutiny/config/scrutiny.yaml 
2020/09/28 17:12:26 No configuration file found at /scrutiny/config/scrutiny.yaml. Skipping

 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
github.com/AnalogJ/scrutiny                     linux.amd64-0.2.1

Start the scrutiny server
2020/09/28 17:12:26 Loading configuration file: /home/parker/.config/scrutiny/config/scrutiny.yaml
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

Trying to connect to database stored: /home/parker/.config/scrutiny/config/scrutiny.db
[GIN-debug] GET    /api/health               --> github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup.func1 (5 handlers)
[GIN-debug] POST   /api/health/notify        --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.SendTestNotification (5 handlers)
[GIN-debug] POST   /api/devices/register     --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.RegisterDevices (5 handlers)
[GIN-debug] GET    /api/summary              --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.GetDevicesSummary (5 handlers)
[GIN-debug] POST   /api/device/:wwn/smart    --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.UploadDeviceMetrics (5 handlers)
[GIN-debug] POST   /api/device/:wwn/selftest --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.UploadDeviceSelfTests (5 handlers)
[GIN-debug] GET    /api/device/:wwn/details  --> github.com/analogj/scrutiny/webapp/backend/pkg/web/handler.GetDeviceDetails (5 handlers)
[GIN-debug] GET    /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] HEAD   /web/*filepath            --> github.com/gin-gonic/gin.(*RouterGroup).createStaticHandler.func1 (5 handlers)
[GIN-debug] GET    /                         --> github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup.func2 (5 handlers)
[GIN-debug] Listening and serving HTTP on 0.0.0.0:8080
```

Config
```
# Commented Scrutiny Configuration File
#
# The default location for this file is ~/scrutiny.yaml.
# In some cases to improve clarity default values are specified,
# uncommented. Other example values are commented out.
#
# When this file is parsed by Scrutiny, all configuration file keys are
# lowercased automatically. As such, Configuration keys are case-insensitive,
# and should be lowercase in this file to be consistent with usage.


######################################################################
# Version
#
# version specifies the version of this configuration file schema, not
# the scrutiny binary. There is only 1 version available at the moment
version: 1

web:
  listen:
    port: 8080
    host: 0.0.0.0
  database:
    # can also set absolute path here
    location: /home/parker/.config/scrutiny/config/scrutiny.db
  src:
    frontend:
      path: /home/parker/.config/scrutiny/web


log:
  file: '' #absolute or relative paths allowed, eg. web.log
  level: INFO

```
