### ISSUE TITLE
[BUG] Scrutiny cannot monitor NVMe without SYS_ADMIN

### ISSUE THREAD

**Issue by agh** [AnalogJ/scrutiny#486]
```
podman exec scrutiny smartctl -j -x /dev/nvme0n1
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      2
    ],
    "svn_revision": "5155",
    "platform_info": "x86_64-linux-6.1.0-9-amd64",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "-j",
      "-x",
      "/dev/nvme0n1"
    ],
    "messages": [
      {
        "string": "Read NVMe Identify Controller failed: NVME_IOCTL_ADMIN_CMD: Permission denied",
        "severity": "error"
      }
    ],
    "exit_status": 2
  },
  "device": {
    "name": "/dev/nvme0n1",
    "info_name": "/dev/nvme0n1",
    "type": "nvme",
    "protocol": "NVMe"
  }
}
```

If you add `--cap SYS_ADMIN` this works just fine, but the templated docker-compose.yml only has SYS_RAWIO which works for SATA-based drives but apparently not for NVMe?

**Comment by AnalogJ** [comment]
Yeah, this is called out in the troubleshooting guide as well as the README - https://github.com/AnalogJ/scrutiny/blob/master/docs/TROUBLESHOOTING_DEVICE_COLLECTOR.md#nvme-drives

**Comment by crispybegs** [comment]
I seem to be having this same issue:

 `"string": "Smartctl open device: /dev/nvme0 failed: Permission denied"`

but my compose has `SYSADMIN` in it?


```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "8880:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /home/crispy/docker/scrutiny/config:/opt/scrutiny/config
      - /home/crispy/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    environment:
      - SCRUTINY_NOTIFY_URLS=slack://https://hooks.slack.com/services/xxxx
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/nvme0"
```
