### ISSUE TITLE
Unable to get SMART drives data in hub/spoke form

### ISSUE THREAD

**Issue by jfromeo** [AnalogJ/scrutiny#488]
First of all, sorry if this is a stupid question as I am not quite tech-savvy.

I own a RPi4B (arm64) running OMV6 and I am running scrutiny in the hub/spoke form with the following docker compose for the 3 docker containers:

```
version: '3.9'
services:
  influxdb:
    image: influxdb:2.2
    container_name: scrutiny-influxdb
    ports:
      - 8086:8086
    volumes:
      - /cache/docker/scrutiny/influxdb:/var/lib/influxdb2
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8086/health]
      interval: 5s
      timeout: 10s
      retries: 20
    restart: unless-stopped
  web:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny-web
    ports:
      - 8080:8080
    volumes:
      - /cache/docker/scrutiny/config:/opt/scrutiny/config
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: influxdb
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8080/api/health]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    restart: unless-stopped
  collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    container_name: scrutiny-collector
    cap_add:
      - SYS_RAWIO
    volumes:
      - /run/udev:/run/udev:ro
    environment:
      COLLECTOR_API_ENDPOINT: http://internal_ip_of_webserver:8080
    depends_on:
      web:
        condition: service_healthy
    devices:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
    restart: unless-stopped
```

smartctl --scan detects correctly my drives in both local and scrutiny-collector docker instance

```
#smartctl -scan
/dev/sdb -d sat # /dev/sdb [SAT], ATA device
/dev/sdc -d sat # /dev/sdc [SAT], ATA device
/dev/sdd -d sat # /dev/sdd [SAT], ATA device
/dev/sde -d sat # /dev/sde [SAT], ATA device
```

scrutiny-influxdb and scrutiny-web are working, accessible on their respective ip:port addresses and with no log errors.
scrutiny-collector only shows "starting cron"

But on scrutiny-web interface no data is shown.

With scrutiny-omnibus image everything works as expected, but I would like to run the hub/client mode as I need to pass the data of another hdd on several local machines to an unique web server.

Thanks so much in advance.
