### ISSUE TITLE
[BUG] Env variables not setting on Scrutiny Web.

### ISSUE THREAD

**Issue by boomam** [AnalogJ/scrutiny#495]
**Describe the bug**
The environment variable `SCRUTINY_WEB_NOTIFY_URLS=` is set on a scrutiny web container (not a collector), however it does not configure/set.
This can be verified (I assume) by looking at the config.yaml file in the config folder within Scrutiny.
Calling `curl -X POST http://localhost:8080/api/health/notify` within a shell session generates no logs.

Comparatively, manually adding the configs to the yaml, restarting the container and re-testing does work.

**Expected behavior**
That the env variable sets.

**Screenshots**
None applicable.

**Log Files**
Nothing in log. _Literally_ blank.

```
version: '3'
services:
  scrutiny-web:
    container_name: scrutiny-web
    hostname: scrutiny-web
    image: ghcr.io/analogj/scrutiny:master-web
    ports:
      - "8080:8080"
    networks:
      - scrutiny
    volumes:
      - /data/container_data/scrutiny-web_config:/opt/scrutiny/config
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=influx_scrutiny
      - SCRUTINY_WEB_INFLUXDB_PORT=8086
      - SCRUTINY_WEB_INFLUXDB_TOKEN=123456
      - SCRUTINY_WEB_INFLUXDB_ORG=scrutiny
      - SCRUTINY_WEB_INFLUXDB_BUCKET=scrutiny
      - SCRUTINY_WEB_NOTIFY_URLS="gotify://gotify.domain.com/123456"

networks:
  scrutiny:
    driver: bridge
```

**The log files will be available on your host in the `config` directory. Please attach them to this issue.**  
Nothing listed in logs. _Literally_ blank.  
&nbsp;  
**Please also provide the output of `docker info`**  
v24.0.2/aarch64
