### ISSUE TITLE
[BUG] Pushover notifications with docker environment variables

### ISSUE THREAD

**Issue by thimplicity** [AnalogJ/scrutiny#498]
**Describe the bug**
Probably rather a human bug here, but I cannot get Pushover (or any notifications for that matter) to work with docker environment variables. I am running scrutiny in a hub-and-spokes model where the web and db run on docker and all servers send their information to the docker container. That works well and only the notifications as missing. I have seen the other issue here on Github on how the config.yaml should be translated into the environment variables, but I cannot get it to run. Also I am a little confused that no config file has been created with docker and now I want to avoid creating one to avoid messing up my setup.

Appreciate some guidance!

**Expected behavior**
Receive notifications with Pushover

```
version: '2.4'

services:
  influxdb:
    image: influxdb:2.2
    ports:
      - '8186:8086'
    volumes:
      - '/docker/scrutiny/influxdb:/var/lib/influxdb2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20

  web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    ports:
      - '8180:8080'
    volumes:
      - '/docker/scrutiny/config:/opt/scrutiny/config'
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
      SCRUTINY_WEB_NOTIFY_URLS: "pushover://shoutrrr:token@token/"
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
```
