### ISSUE TITLE
Can't access webui

### ISSUE THREAD

**Issue by barukh27** [AnalogJ/scrutiny#526]
**Describe the bug**
 I cannot connect to the scrutiny container using the docker host name/IP and port specified in the container, using a web browser, e.g., http://docker1:8080. Note that I can connect to the influxdb container using http://docker1:8086.

I used this docker-compose template:

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
     ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /mnt/dietpi_userdata/scrutiny:/opt/scrutiny/config
      - /mnt/dietpi_userdata/scrutiny/influxdb2:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
    restart: unless-stopped

Thank you for your help.

**Comment by icf20** [comment]
The config is partial because is missing the config files 

here is a example of all in one for copy paste

```
version: "3.4"
# https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml
services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.1-alpine
    ports:
      - 8086:8086
    volumes:
      - /changeme/config/influxdb/scrutiny/db:/var/lib/influxdb2
      - /changeme/config/influxdb/scrutiny/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminABC123.,make_sure_the_pwd_has_the_correct_format
      - DOCKER_INFLUXDB_INIT_ORG=changeme
      - DOCKER_INFLUXDB_INIT_BUCKET=scrutiny
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=11546564564654564545643645747673changeme
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-web
    ports:
      - 8080:8080
    volumes:
      - /changeme/config/scrutiny/config:/opt/scrutiny/config
    environment:
      - SCRUTINY_WEB_INFLUXDB_HOST=influxdb
      - SCRUTINY_WEB_INFLUXDB_PORT=8086
      - SCRUTINY_WEB_INFLUXDB_TOKEN=11546564564654564545643645747673changeme
      - SCRUTINY_WEB_INFLUXDB_ORG=changeme
      - SCRUTINY_WEB_INFLUXDB_BUCKET=scrutiny
    depends_on:
      - influxdb
    restart: unless-stopped

## u can copy paste this into other hosts and send the data to  scrutiny:master-web
# version: "3.4"
# services:
# https://github.com/AnalogJ/scrutiny/blob/master/docker/example.hubspoke.docker-compose.yml
  collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'

    cap_add:
      - SYS_RAWIO
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: 'http://<-master-web--changeme>:8080'
    devices:
      - "/dev/sda"
      - "/dev/blabla bla change me"

```

check if  scrutiny-collector-1 and the host see the disks with `smartctl --scan` then `scrutiny-collector-metrics run`
