### ISSUE TITLE
[BUG] Could not retrieve device information

### ISSUE THREAD

**Issue by arthurcruz1** [AnalogJ/scrutiny#538]
Drive is not shown on the WebUI

`docker compose exec scrutiny /opt/scrutiny/bin/scrutiny-collector-metrics run`

```
Error:
Could not retrieve device information for sda: exit status 2  type=metrics
```

`smartctl --info --json --device sat /dev/sda  type=metrics`

```
smartctl --info --json --device sat /dev/sda  type=metrics
{
  "json_format_version": [
    1,
    0
  ],
  "smartctl": {
    "version": [
      7,
      3
    ],
    "svn_revision": "5338",
    "platform_info": "aarch64-linux-5.15.0-1042-raspi",
    "build_info": "(local build)",
    "argv": [
      "smartctl",
      "--info",
      "--json",
      "--device",
      "sat",
      "/dev/sda",
      "type=metrics"
    ],
    "messages": [
      {
        "string": "ERROR: smartctl takes ONE device name as the final command-line argument.",
        "severity": "error"
      }
    ],
    "exit_status": 1
  }
}
```

`docker logs scrutiny`

```
 ___   ___  ____  __  __  ____  ____  _  _  _  _
/ __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
\__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
(___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
AnalogJ/scrutiny/metrics                                dev-0.7.2

time="2023-11-01T14:38:46Z" level=info msg="Verifying required tools" type=metrics
time="2023-11-01T14:38:46Z" level=info msg="Executing command: smartctl --scan --json" type=metrics
time="2023-11-01T14:38:46Z" level=info msg="Executing command: smartctl --info --json --device sat /dev/sda" type=metrics
time="2023-11-01T14:38:46Z" level=error msg="Could not retrieve device information for sda: exit status 2" type=metrics
time="2023-11-01T14:38:46Z" level=info msg="Sending detected devices to API, for filtering & validation" type=metrics
time="2023-11-01T14:38:46Z" level=info msg="127.0.0.1 - 8848b38a722f [01/Nov/2023:14:38:46 +0000] \"POST /api/devices/register\" 200 40 \"\" \"Go-http-client/1.1\" (1ms)" clientIP=127.0.0.1 hostname=8848b38a722f latency=1 method=POST path=/api/devices/register referer= respLength=40 statusCode=200 type=web userAgent=Go-http-client/1.1
time="2023-11-01T14:38:46Z" level=info msg="Main: Completed" type=metrics
```

`smartctl --scan`

```
/dev/sda -d sntasmedia # /dev/sda [USB NVMe ASMedia], NVMe device
```

Using omnibus image

**Comment by vincejv** [comment]
@arthurcruz1 
> --cap-add SYS_RAWIO is necessary to allow smartctl permission to query your device SMART data
NOTE: If you have NVMe drives, you must add --cap-add SYS_ADMIN as well. See issue https://github.com/AnalogJ/scrutiny/issues/26#issuecomment-696817130

**Comment by arthurcruz1** [comment]
> @arthurcruz1
> 
> > --cap-add SYS_RAWIO is necessary to allow smartctl permission to query your device SMART data
> > NOTE: If you have NVMe drives, you must add --cap-add SYS_ADMIN as well. See issue [#26 (comment)](https://github.com/AnalogJ/scrutiny/issues/26#issuecomment-696817130)

@vincejv This issue occurs with SYS_ADMIN added to the docker-compose file

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "8082:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
    network_mode: bridge
    restart: unless-stopped
```

Running the container with `--privileged` also returns the same error
