### ISSUE TITLE
Setup notification error with docker-compose version 3.5 with image omnibus

### ISSUE THREAD

**Issue by Chianta** [AnalogJ/scrutiny#562]
Setup Notification in docker-compose version 3.5 with image omnibus send me an error:

_"failed to deploy a stack: validating /data/compose/8/docker-compose.yml: services.scrutiny Additional property notify is not allowed"_

My stack is:

```
version: '3.5'
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "10081:8080" # webapp
      - "18086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /appdata/scrutiny/config:/opt/scrutiny/config
      - /appdata/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
    notify:
      urls:
        - "telegram://************@telegram?channels=*************"
```

How can I correctly set notification with Telegram bot?
