### ISSUE TITLE
[BUG] collector ignores some setting in config file on macOS

### ISSUE THREAD

**Issue by phirestalker** [AnalogJ/scrutiny#565]
I have the server portion running in docker on my linux machine. The problem system is an M1 mac

**Describe the bug**
I have set the host id and some device settings. When the collector is run, it will see the api and command settings, but will not use the host id. Also, it is getting stats for a device that I have set to ignore. There is only one real device (other than USB). smartctl is picking up the container as a drive, which is why I was trying to ignore a device.

**Expected behavior**
I expected the host id and device settings to be honored like they are on other platforms. I also expected it to show me stats for disk0 since I set that up in the config file.

**Screenshots**
<img width="926" alt="Screenshot 2024-01-12 at 4 02 00 PM" src="https://github.com/AnalogJ/scrutiny/assets/7477095/dccf69c3-cd34-4214-8f23-c8da8b44629a">
**Config file for collector**
```
# Commented Scrutiny Configuration File
#
# The default location for this file is /opt/scrutiny/config/collector.yaml.
# In some cases to improve clarity default values are specified,
# uncommented. Other example values are commented out.
#
# When this file is parsed by Scrutiny, all configuration file keys are
# lowercased automatically. As such, Configuration keys are case-insensitive,
# and should be lowercase in this file to be consistent with usage.


######################################################################
# Version
#
# version specifies the version of this configuration file schema, not
# the scrutiny binary. There is only 1 version available at the moment
version: 1

# The host id is a label used for identifying groups of disks running on the same host
# Primiarly used for hub/spoke deployments (can be left empty if using all-in-one image).
host:
  id: "Neal's Mac Mini"


# This block allows you to override/customize the settings for devices detected by
# Scrutiny via `smartctl --scan`
# See the "--device=TYPE" section of https://linux.die.net/man/8/smartctl
# type can be a 'string' or a 'list'
devices:
  - device: /dev/disk0
    type: 'auto'
 
  - device: /dev/disk3
    ignore: true

#  # example for forcing device type detection for a single disk
#  - device: /dev/sda
#    type: 'sat'
#
#  # example for using `-d sat,auto`, notice the square brackets (workaround for #418)
#  - device: /dev/sda
#    type: ['sat,auto']
#
#  # example to show how to ignore a specific disk/device.
#  - device: /dev/sda
#    ignore: true
#
#  # examples showing how to force smartctl to detect disks inside a raid array/virtual disk
#  - device: /dev/bus/0
#    type:
#      - megaraid,14
#      - megaraid,15
#      - megaraid,18
#      - megaraid,19
#      - megaraid,20
#      - megaraid,21
#
#  - device: /dev/twa0
#    type:
#      - 3ware,0
#      - 3ware,1
#      - 3ware,2
#      - 3ware,3
#      - 3ware,4
#      - 3ware,5
#
#  # example to show how to override the smartctl command args (per device), see below for how to override these globally.
#  - device: /dev/sda
#    commands:
#      metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
#      metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.


#log:
#  file: '' #absolute or relative paths allowed, eg. web.log
#  level: INFO
#
api:
  endpoint: 'http://192.168.133.138:8080'
#  endpoint: 'http://localhost:8080/custombasepath'
# if you need to use a custom base path (for a reverse proxy), you can add a suffix to the endpoint.
#  See docs/TROUBLESHOOTING_REVERSE_PROXY.md for more info,

# example to show how to override the smartctl command args globally
commands:
  metrics_smartctl_bin: '/opt/homebrew/bin/smartctl' # change to provide custom `smartctl` binary path, eg. `/usr/sbin/smartctl`
#  metrics_scan_args: '--scan --json' # used to detect devices
#  metrics_info_args: '--info --json' # used to determine device unique ID & register device with Scrutiny
#  metrics_smart_args: '--xall --json' # used to retrieve smart data for each device.


########################################################################################################################
# FEATURES COMING SOON
#
# The following commented out sections are a preview of additional configuration options that will be available soon.
#
########################################################################################################################

#collect:
#  long:
#    enable: false
#    command: ''
#  short:
#    enable: false
#    command: ''
```

**Log Files**
I tried to modify my setup to get the logs, but I couldn't get it to work. Using the plain docker image and running it like the instructions say would not diagnose my issue since it is only one host with this problem. If there is a way to set debug mode on just the collector, or through my compose file for the server, I will be happy to try that.
