### ISSUE TITLE
[BUG]   Error: short-name "influxdb:2.7" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" 

### ISSUE THREAD

**Issue by heapxor** [AnalogJ/scrutiny#567]
**Describe the bug**
Trying to run scrunity via podman, getting issue, log below

 Error: short-name "influxdb:2.7" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf" 

**Expected behavior**
run the pod

**Screenshots**
```
podman-compose up
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 3.4.4
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=scrunity', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_scrunity --infra=false --share=
3d9e0505a55f930fab490d90f11051179ecbe9d133493a0bafd40c3822621b4a
exit code: 0
['podman', 'network', 'exists', 'scrunity_default']
podman create --name=scrunity_influxdb_1 --pod=pod_scrunity --label io.podman.compose.config-hash=17838a7e4873d56c69c33e5c87e760ee94bb2c3db8f887364bd6fe60eab61eb8 --label io.podman.compose.project=scrunity --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@scrunity.service --label com.docker.compose.project=scrunity --label com.docker.compose.project.working_dir=/home/heap/scrunity --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=influxdb -v /home/heap/scrunity/influxdb:/var/lib/influxdb2 --net scrunity_default --network-alias influxdb -p 8086:8086 --healthcheck-command /bin/sh -c curl' '-f' 'http://localhost:8086/health --healthcheck-interval 5s --healthcheck-timeout 10s --healthcheck-retries 20 influxdb:2.7
**Error: short-name "influxdb:2.7" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"**
exit code: 125
['podman', 'network', 'exists', 'scrunity_default']
podman create --name=scrunity_web_1 --pod=pod_scrunity --requires=scrunity_influxdb_1 --label io.podman.compose.config-hash=17838a7e4873d56c69c33e5c87e760ee94bb2c3db8f887364bd6fe60eab61eb8 --label io.podman.compose.project=scrunity --label io.podman.compose.version=1.0.7 --label PODMAN_SYSTEMD_UNIT=podman-compose@scrunity.service --label com.docker.compose.project=scrunity --label com.docker.compose.project.working_dir=/home/heap/scrunity --label com.docker.compose.project.config_files=compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web -e SCRUTINY_WEB_INFLUXDB_HOST=influxdb -v /home/heap/scrunity/config:/opt/scrutiny/config --net scrunity_default --network-alias web -p 8080:8080 --healthcheck-command /bin/sh -c curl' '-f' 'http://localhost:8080/api/health --healthcheck-interval 5s --healthcheck-timeout 10s --healthcheck-start-period 10s --healthcheck-retries 20 ghcr.io/analogj/scrutiny:master-web
Error: "scrunity_influxdb_1" is not a valid container, cannot be used as a dependency: no container with name or ID "scrunity_influxdb_1" found: no such container
exit code: 125
podman start -a scrunity_influxdb_1
Error: no container with name or ID "scrunity_influxdb_1" found: no such container
exit code: 125
podman start -a scrunity_web_1
Error: no container with name or ID "scrunity_web_1" found: no such container
exit code: 125
```

cat compose.yml
```

version: '2.4'

services:
  influxdb:
    image: influxdb:2.7
    ports:
      - '8086:8086'
    volumes:
      - './influxdb:/var/lib/influxdb2'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20

  web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    ports:
      - '8080:8080'
    volumes:
      - './config:/opt/scrutiny/config'
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s


```
