### ISSUE TITLE
[BUG] Deleting a device in the Scrutiny UI does not delete the influxdb data and persists the device across docker restarts

### ISSUE THREAD

**Issue by delize** [AnalogJ/scrutiny#572]
**Describe the bug**
When a device has been removed from a host and you wish to delete the device using
<img width="264" alt="Screenshot 2024-01-30 at 12 49 57" src="https://github.com/AnalogJ/scrutiny/assets/4028612/57132e75-ed64-4fa5-ac77-6c80224c1d89">

The device gets removed initially from the UI.

If the docker container restarts, the previously deleted disk's information gets reloaded into the environment. 

When using ZFS or hots-swap disks this causes incorrect information to be present in scrutiny.

**Expected behavior**
When delete device (above) is clicked. All data from influx should be removed and the device should no longer appear in the Web UI.

**Screenshots**
A disk that has been removed from the host, the data has been deleted, but, still exists in the Web UI.
<img width="731" alt="Screenshot 2024-01-30 at 12 52 06" src="https://github.com/AnalogJ/scrutiny/assets/4028612/edf7479d-51eb-4679-a8f6-1985b00bec37">

**Log Files**
N/A

```
    scrutiny:
        container_name: scrutiny
        image: ghcr.io/analogj/scrutiny:master-omnibus
        privileged: true
        cap_add:
            - SYS_RAWIO
            - SYS_ADMIN
        # ports:
        #     - "8082:8080" # webapp
            # - "8087:8086" # influxDB admin
        environment:
            - SCRUTINY_WEB_INFLUXDB_INIT_USERNAME=${SCRUTINY_WEB_INFLUXDB_INIT_USERNAME}
            - SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD=${SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD}
        volumes:
            - /run/udev:/run/udev:ro
            - ${BASE_PATH}/scrutiny/config:/opt/scrutiny/config
            - ${BASE_PATH}/influxdb:/opt/scrutiny/influxdb
        restart: 'unless-stopped'
        devices:
            # - "/dev/sda"
            - "/dev/sdb"
            - "/dev/sdc"
            - "/dev/sdd"
            - "/dev/sde"
            - "/dev/sdf"
            - "/dev/sdg"
            - "/dev/sdh"
            - "/dev/nvme0"
            - "/dev/nvme1"
        networks:
            - lame
            - backend
# in another terminal trigger the collector
docker exec scrutiny scrutiny-collector-metrics run

```
Note that even though the drive is commented out in the above compose file, it keeps re-appearing, and also finding the /dev/sda due to the other cap_add & priv settings.

I can't currently upload the log file, but, I will be able to when I am on the same network as the device.

**Docker Info**

``` docker info                                                                                                                                                                      [12:55:03]
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 52
  Running: 48
  Paused: 0
  Stopped: 4
 Images: 49
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-15-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 94.06GiB
 Name: OMIT
 ID: OMIT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
