### ISSUE TITLE
[FEAT] Exclude drives

### ISSUE THREAD

**Issue by SplinterHead** [AnalogJ/scrutiny#588]
**Is your feature request related to a problem? Please describe.**
I have a hardware RAID controller (Dell PERC) that I have configured to show the drives connected. When the container (re)starts, all the configured drives attached to the RAID controller show up green, but it also shows up the physical drives which are red as Scrutiny cannot read the data for these drives. 

**Describe the solution you'd like**
I would like to be able to (probably in the `collector.yaml`) define drives that are excluded from Scrutiny's dashboard. They aren't mounted to the docker container, but the container is running in `privileged` mode - this is so I can mount `/dev/bus/*`

**Additional context**
Below is the `docker-compose.yaml` file I am running 
```yaml
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    networks:
      - nginx
    cap_add:
      - SYS_RAWIO
    privileged: true
    volumes:
      - /run/udev:/run/udev:ro
      - /storage/data/scrutiny/config:/opt/scrutiny/config
      - /storage/data/scrutiny/influx:/opt/scrutiny/influxdb
    devices:
      - "/dev/sdk" # OS Disk
      - "/dev/bus/0" # Dell PERC H710
      - "/dev/bus/1" # Dell PERC H810
```
