### ISSUE TITLE
[BUG] When collector.yaml exists scrutiny collector never starts, only showing "Loading configuration file"

### ISSUE THREAD

**Issue by EpicLPer** [AnalogJ/scrutiny#642]
**Describe the bug**
I've created a `collector.yaml` file in `/opt/scrutiny/config` to change some of the arguments for smartctl (forcing it to go SAT/ATA). However no matter what I try it always just stops at "Loading configuration file" and never continues, even if I comment essentially every line except commands in that file. Even debug mode doesn't give more than just that line.

**Expected behavior**
Scrutiny should use the new arguments for smartctl and run properly.

**Screenshots**
\---

**Log Files**
> Running with commented `commands:` section
![image](https://github.com/AnalogJ/scrutiny/assets/8442196/516d82bf-525b-4d5f-8448-b45970b64423)

> Running with uncommented `commands:` section and the following settings:
```
commands:
   metrics_info_args: '--device=sat --info --json'
   metrics_smart_args: '--device=sat --xall --json'
```
![image](https://github.com/AnalogJ/scrutiny/assets/8442196/65a299b0-3ffd-4ab7-ba6e-f34da52f98c1)

---

My current `collector.yaml` is as follows:
```
version: 1

host:
  id: 'PBS1'

devices:

log:
  file: '/opt/scrutiny/debug.log' #absolute or relative paths allowed, eg. web.log
  level: DEBUG

api:
  endpoint: "http://XXXX:8080"

commands:
  metrics_info_args: '--device=sat --info --json' # used to determine device unique ID & register device with Scrutiny
  metrics_smart_args: '--device=sat --xall --json' # used to retrieve smart data for each device.
#  metrics_smartctl_bin: 'smartctl' # change to provide custom `smartctl` binary path, eg. `/usr/sbin/smartctl`
#  metrics_scan_args: '--scan --json' # used to detect devices

```

**Comment by paulmorabito** [comment]
Having the same issue after using this a number of years but needing to rebuild due to some system issues.

**Comment by didi-home** [comment]
I think I have the same issue. I tried to use a collector.yaml for 3ware type disks. However, when adding a collector.yaml, not even a disk attached to standard controller is collected anymore :-(

My guess would also be that #668 is related and possibly other bugs.

**Comment by siebert** [comment]
I could work around the issue by moving the problematic generic metrics_info_args setting to a specific device section, here is my working collector.yaml:

```
version: 1

devices:
  - device: /dev/sda
    commands:
      metrics_info_args: "--device=sat --info --json"
```
