### ISSUE TITLE
[BUG] No disks displayed 

### ISSUE THREAD

**Issue by paulmorabito** [AnalogJ/scrutiny#668]
Hi,

I'm running Scrutiny on a  QNAP TS453Be via docker. The container config is as folows:

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny-new
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8180:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - /share/persistent/scrutiny/:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
 ```

I have created a collector.yaml as previously I had trouble with getting the smart disk info (#560 ). The collector yaml is as follows:

```
devices:
  # example for forcing device type detection for a single disk
  - device: /dev/sda
    type: 'sat'
  - device: /dev/sdb
    type: 'sat'
  - device: /dev/sdc
    type: 'sat'
  - device: /dev/sdd
    type: 'sat'
commands:
  #  metrics_scan_args: '--scan --json' # used to detect devices
  #  metrics_info_args: '--info --json' # used to determine device unique ID & register device with Scrutiny
  metrics_smart_args: '--xall --device=sat --json' # used to retrieve smart data for each device.
```

I can access smartctl disk info from the command line though the web UI is empty of all disk related information. Trying to manually trigger the collector gives no further info:

```
[~] # docker exec 39cfd4e5778b /opt/scrutiny/bin/scrutiny-collector-metrics run --debug
2024/07/27 11:16:39 Loading configuration file: /opt/scrutiny/config/collector.yaml
[~] #
```

Any ideas on what I can do to debug further?
