### ISSUE TITLE
Provide the app in TrueNAS 24.10 Electric Eel

### ISSUE THREAD

**Issue by RebelliousX** [AnalogJ/scrutiny#681]
TrueNAS upcoming Electric Eel v24.10 will move apps from Kubernetes to Docker. And once I did upgrade
from Dragonfish to the new Beta1, I can't find Scrutiny in the list of Apps to be installed.

I am not sure if you guys maintain the App for TrueNAS or not, but if you do, please consider adding it
to support the newer version. I really love Scrutiny.

Edit: I was able to install Scrutiny in Portainer in TrueNAS. But I still wish it gets to be an official app
from the list of offered apps in TrueNAS. Issue with Portainer? Scrutiny doesn't show  up in the list
of running apps unless I open Portainer's webUI. 

One thing I noticed, that I needed to modify the[ yaml for docker compose](https://github.com/AnalogJ/scrutiny/blob/master/docker/example.omnibus.docker-compose.yml) to make it work with NVME drive.

```
cap_add:
      - SYS_RAWIO
      - SYS_ADMIN # SYS_ADMIN is needed to get S.M.A.R.T sensors' readings for NVME drives. 
```

without `SYS_ADMIN` I was getting NVME status failed for some reason for `/dev/nvme0`
And the version line also throws a warning that it was ignored and obsolete too. So I removed that too
per the suggestion of that warning.

Note that I was able to install Scrutiny before when TrueCharts was supported, but now discontinued.
Scrutiny was in TrueCharts.

**Comment by tismofied** [comment]
I would love this addition as well!

**Comment by KaiStarkk** [comment]
+1, would be great to have a TrueNAS Scale app for Scrutiny.
Also, it would be a good way to clarify if any configuration is needed to avoid clashes between Scrutiny and the built in cron jobs on TrueNAS (assume Scrutiny is just collecting tests, not orchestrating them?)

**Comment by RebelliousX** [comment]
It has been added to TrueNAS, but I am stuck trying to install it. Somehow it is a lot easier installing it from Portainer with a modified YAML file (new stack in portainer).

In TrueNAS, it is asking to add disks, I get the field "Host Disk Path" since I can get those using `sudo smartctl --scan`. But I don't know what it is asking exactly when it asks for a required field "Container Disk Path".

Any thoughts on how to get the container disk path?

My portainer stack yaml code if this helps:
```yaml
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN # SYS_ADMIN is needed to get S.M.A.R.T sensors' readings for NVME drives. Without it we get error.
    ports:
      - "30001:8080" # webapp (note that, the left is for host, and right for container, I changed the left)
      - "30002:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/nvme0"
      # get list of devices by running: "sudo smartctl --scan" in TrueNAS shell console.
```
