### ISSUE TITLE
Error gathering deevice information while adding custom device "/dev/sda": no such file or directory

### ISSUE THREAD

**Issue by LordVZlomka** [AnalogJ/scrutiny#715]
Hi,

I'm trying to install Scrutiny via docker with this compose file:

```
version: '3.5'

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /volume1/docker/scrutiny/run/udev:/run/udev:ro
      - /volume1/docker/scrutiny/config:/opt/scrutiny/config
      - /volume1/docker/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"

```

When I try to build, I get an error `error gathering device information while adding custom device "/dev/sda": no such file or directory`
