### ISSUE TITLE
[BUG] `scan_smart_devices: glob(3) aborted matching pattern /dev/discs/disc*`

### ISSUE THREAD

**Issue by jo-chemla** [AnalogJ/scrutiny#751]
**Describe the bug**
On an older synology NAS, scrutiny shows no drives/SMART tests in the webui. Testing `smartctl` via SSH yields the below error: 

```bash
smartctl --scan 
scan_smart_devices: glob(3) aborted matching pattern /dev/discs/disc*
```

Note: trying the bellow yields: 
```bash
smartctl --scan /dev/sata*
# scan_smart_devices: DEVICESCAN with pattern not implemented yet
```

See resolution [here](https://www.nas-forum.com/forum/topic/77940-scrutiny/): It is required in that case to tell scrutiny what devices to test drives for, via the `collector.yaml` file 
```yaml
devices:
   - device: /dev/sata1
     type: 'sat'
```

**Expected behavior**
The error could be made more apparent in logs or the webui (for web/spoke or full scrutiny), or an alternative smartctl mode could be used to bypass the error

**Comment by DD1TTY** [comment]
I am having this same issue on my DS1522+ with scrutiny running in a container according to these installation instructions:
https://drfrankenstein.co.uk/scrutiny-in-container-manager-on-a-synology-nas/

Here's my collector.yaml file:

```
YAML

version: 1
host:
  id: ""
devices:
  - device: /dev/sata1
    type: 'sat'
  - device: /dev/sata2
    type: 'sat'
  - device: /dev/sata3
    type: 'sat'
  - device: /dev/sata4
    type: 'sat'
  - device: /dev/nvme0n1
    type: 'nvme'
  - device: /dev/nvme1n1
    type: 'nvme'
```

But I still can't get any disks to show up in the WebUI.

Is there still something messed up with my collector.yaml file?

**Comment by DrFrankensteinUK** [comment]
Hey. 

Can you connect to the containers terminal by going into it within Container Manager, Click Action, Open Terminal then click Create, and it should give you a BASH window in the list.. 

Then type smartctl --xall /dev/sata1

You may need to wait a few minutes and see if the WebUI updates - I tested this my end and I see the time of the last scan change in line with when I run the command,.

**Comment by DD1TTY** [comment]
Hey @DrFrankensteinUK , thanks for the reply! I had also posted a comment on the guide yesterday; sorry for the duplicate posts!

I just did that one at a time for each of my drives and their smart data seemed to show up in the terminal window, but I still don't have anything showing up in the scrutiny dashboard.

Here are my config files: https://paste.drfrankenstein.co.uk/?4b9142dd459777a9#C6LWx35DHwshvHPXzsDfrVVkvaSRQEc1tBBRsnNGsbvd

I SSH-ed into my NAS to run sudo smartctl --xall /dev/sata1-4, and found the following (not sure if relevant or not)

/dev/sata1 = Seagate Iron Wolf
/dev/sata2= Seagate Iron Wolf
/dev/sata3=ST16000NT001-3LV101, Device is: Not in smartctl database, SMART support is still Available and Enabled, however
/dev/sata4=Iron Wolf PRO

I don't seem to be able to run the same command for /dev/nvme0n1 or /dev/nvme1n1 or /dev/nvme0n1p1 or /dev/nvme1n1p1, not sure if that's supposed to work or not. I can use sudo smartctl /dev/nvme0n1p1 which successfully outputs NVMe device successfully opened

The smartctl --xall /dev/nvme0n1 does report SMART data when run in the container terminal

**Comment by DrFrankensteinUK** [comment]
Apologies, been very short on free time recently! In the collector.yaml add this under each device. it's from the example collector not sure if it will help?!

```
  - device: /dev/sata1
    type: 'sat'
    commands:
      metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
      metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
```

**Comment by DD1TTY** [comment]
Hi DrFrankensteinUK, no worries, this is not at all pressing! :)


I just stopped the project/container and updated my collector.yaml file accordingly:

```
YAML

version: 1
host:
  id: ""
devices:
  - device: /dev/sata1
    type: 'sat'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
  - device: /dev/sata2
    type: 'sat'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
  - device: /dev/sata3
    type: 'sat'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
  - device: /dev/sata4
    type: 'sat'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
  - device: /dev/nvme0n1
    type: 'nvme'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
  - device: /dev/nvme1n1
    type: 'nvme'
    metrics_info_args: '--info --json -T permissive' # used to determine device unique ID & register device with Scrutiny
    metrics_smart_args: '--xall --json -T permissive' # used to retrieve smart data for each device.
#  - device: /dev/usb1
#    type: 'sat'
#  - device: /dev/usb2
#    type: 'sat'
```

I restarted the container/project, waited for a few minutes, and then since there was no change I again SSH-ed in and ran 

```
sudo docker exec scrutiny /opt/scrutiny/bin/scrutiny-collector-metrics run
```

...but there are still no drives showing up in my Scrutiny dashboard. 

FYI when I got my Synology NAS two years ago, I used all of your guides to set it up exactly the same as yours (Servarr stack, qbittorrent+glutun, Overseerr, etc), using the exact same directory structure. Not sure if that is helpful in troubleshooting this or not.
