### ISSUE TITLE
Add documentation for telegram `message_thread_id`

### ISSUE THREAD

**Issue by MrCaringi** [AnalogJ/scrutiny#765]
## Describe the bug
Notification doesnt work when I try to use `message_thread_id` as query parameter

## Expected behavior
A message should sent to a Telegram Group/Topic

##  Scrutiny.yml
This is the config I use (of course I am posting fake API-TOKEN and Group values)
```yml
notify:
  urls:
    - "telegram://123:abc@telegram?channels=-123&message_thread_id=123"
```

## Log Files
```shell
scrutiny-web  | time="2025-04-12T17:03:30Z" level=error msg="An error occurred while sending notifications telegram://123:abc@telegram?channels=-123&message_thread_id=123: error initializing router services: message_thread_id is not a valid config key [channels chats notification parsemode preview title]" type=web
scrutiny-web  | time="2025-04-12T17:03:30Z" level=error msg="One or more notifications failed to send successfully. See logs for more information." type=web
scrutiny-web  | time="2025-04-12T17:03:30Z" level=error msg="An error occurred while sending test notification error initializing router services: message_thread_id is not a valid config key [channels chats notification parsemode preview title]" type=web
```

## docker compose used
```yml
services:
  influxdb:
    image: influxdb:2.2
    container_name: scrutiny-db
    restart: always
    ports:
      - '8086:8086'
    volumes:
      - /mnt/services/scrutiny/influxdb:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20

# TEST notification
# docker exec -it scrutiny-web curl -X POST http://localhost:8080/api/health/notify

  web:
    image: 'ghcr.io/analogj/scrutiny:master-web'
    container_name: scrutiny-web
    restart: always
    ports:
      - '8065:8080'
    volumes:
      - /mnt/services/scrutiny/web:/opt/scrutiny/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
```
## Docker Info output
```shell
Client: Docker Engine - Community
 Version:    28.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.22.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.34.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 28.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05044ec0a9a75232cad458027ca83437aae3f4da
 runc version: v1.2.5-0-g59923ef
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.12-8-pve
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1GiB
 Name: services
 ID: abd7ef88-f61b-4565-9341-f20d41138a41
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  ::1/128
  127.0.0.0/8
 Live Restore Enabled: false
```
