### ISSUE TITLE
[BUG] /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_migrations.go:409 attempt to write a readonly database (8)

### ISSUE THREAD

**Issue by Dinth** [AnalogJ/scrutiny#772]
**Describe the bug**
Im trying to improve security of scrutiny.
Unfortunately after adding CAP_DROP: ALL, it fails to start. 

**Expected behavior**
The webapp container should just work, or the expected CAPs should be documented.

**Docker Compose**

```
name: scrutiny
services:
  scrutiny-collector:
    cap_add:
      - SETGID
      - SETUID
      - SYS_RAWIO
    cap_drop:
      - ALL
    command:
      - /entrypoint-collector.sh
    container_name: scrutiny-collector
    devices:
      - source: /dev/sda
        target: /dev/sda
        permissions: rwm
      - source: /dev/sdb
        target: /dev/sdb
        permissions: rwm
      - source: /dev/sdc
        target: /dev/sdc
        permissions: rwm
      - source: /dev/sdd
        target: /dev/sdd
        permissions: rwm
      - source: /dev/sde
        target: /dev/sde
        permissions: rwm
      - source: /dev/sdf
        target: /dev/sdf
        permissions: rwm
      - source: /dev/sdg
        target: /dev/sdg
        permissions: rwm
      - source: /dev/sdh
        target: /dev/sdh
        permissions: rwm
      - source: /dev/sdi
        target: /dev/sdi
        permissions: rwm
      - source: /dev/sdj
        target: /dev/sdj
        permissions: rwm
    environment:
      COLLECTOR_API_ENDPOINT: "http://10.10.1.13:93"
    hostname: scrutiny-collector
    image: ghcr.io/analogj/scrutiny:master-collector
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      scrutiny: null
    restart: unless-stopped
    volumes:
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
        bind:
          create_host_path: true
    working_dir: /opt/scrutiny
  scrutiny-web:
    cap_drop:
      - ALL
    command: ['/opt/scrutiny/bin/scrutiny','start']
    user: "${DOCKER_PUID}:${DOCKER_PGID}"
    container_name: scrutiny-web
    environment:
      PATH: /opt/scrutiny/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      SCRUTINY_WEB_INFLUXDB_HOST: "10.10.1.11"
      SCRUTINY_WEB_INFLUXDB_ORG: "scrutiny"
      SCRUTINY_WEB_INFLUXDB_PORT: "8086"
      SCRUTINY_WEB_NOTIFY_URLS: "${SCRUTINY_WEB_NOTIFY_URLS}"
      SCRUTINY_WEB_INFLUXDB_TOKEN: "${SCRUTINY_WEB_INFLUXDB_TOKEN}"
    hostname: scrutiny-web
    image: ghcr.io/analogj/scrutiny:master-web
    ipc: private
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      scrutiny: null
    ports:
      - mode: ingress
        target: 8080
        published: "93"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/docker/scrutiny/scrutiny_config
        target: /opt/scrutiny/config
        bind:
          create_host_path: true
    working_dir: /opt/scrutiny
networks:
  scrutiny:
    name: scrutiny
    driver: bridge
```

**Log Files**

```
scrutiny-collector  | 2025-05-04T06:12:07.786218178Z starting cron
scrutiny-web        | 2025-05-04T06:13:04.871081430Z 2025/05/04 06:13:04 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.
scrutiny-web        | 2025-05-04T06:13:04.871424054Z time="2025-05-04T06:13:04Z" level=info msg="Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:13:04.872250951Z time="2025-05-04T06:13:04Z" level=info msg="Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:13:04.872269540Z time="2025-05-04T06:13:04Z" level=info msg="InfluxDB certificate verification: true\n" type=web
scrutiny-web        | 2025-05-04T06:13:04.912826950Z time="2025-05-04T06:13:04Z" level=info msg="Database migration starting. Please wait, this process may take a long time...." type=web
scrutiny-web        | 2025-05-04T06:13:04.915789474Z 
scrutiny-web        | 2025-05-04T06:13:04.915815271Z 2025/05/04 06:13:04 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_migrations.go:409 attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:13:04.915829153Z [0.202ms] [rows:0] ALTER TABLE `devices` ADD `archived` numeric
scrutiny-web        | 2025-05-04T06:13:04.915841915Z time="2025-05-04T06:13:04Z" level=error msg="Database migration failed with error. \n Please open a github issue at https://github.com/AnalogJ/scrutiny and attach a copy of your scrutiny.db file. \n attempt to write a readonly database (8)" type=web
scrutiny-web        | 2025-05-04T06:13:04.917984704Z panic: attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:13:04.917994653Z 
scrutiny-web        | 2025-05-04T06:13:04.917998666Z goroutine 1 [running]:
scrutiny-web        | 2025-05-04T06:13:04.918002701Z github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x11d5768?, 0xc000192d80?}, {0x11d9e70?, 0xc0004b9880?})
scrutiny-web        | 2025-05-04T06:13:04.918010628Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:15 +0xd6
scrutiny-web        | 2025-05-04T06:13:04.918015480Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc00018b2f0, 0x1046d81?)
scrutiny-web        | 2025-05-04T06:13:04.918020743Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xa5
scrutiny-web        | 2025-05-04T06:13:04.918025671Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc00018b2f0)
scrutiny-web        | 2025-05-04T06:13:04.918040840Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:84 +0x12c
scrutiny-web        | 2025-05-04T06:13:04.918046235Z main.main.func2(0xc0003bdf40)
scrutiny-web        | 2025-05-04T06:13:04.918056695Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:133 +0x39c
scrutiny-web        | 2025-05-04T06:13:04.918068946Z github.com/urfave/cli/v2.(*Command).Run(0xc00047f200, 0xc0003bddc0)
scrutiny-web        | 2025-05-04T06:13:04.918079436Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x5c8
scrutiny-web        | 2025-05-04T06:13:04.918124783Z github.com/urfave/cli/v2.(*App).RunContext(0xc0003e8480, {0x11ccb68?, 0xc00019a020}, {0xc000198000, 0x2, 0x2})
scrutiny-web        | 2025-05-04T06:13:04.918133242Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0xbac
scrutiny-web        | 2025-05-04T06:13:04.918137932Z github.com/urfave/cli/v2.(*App).Run(...)
scrutiny-web        | 2025-05-04T06:13:04.918141712Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
scrutiny-web        | 2025-05-04T06:13:04.918166364Z main.main()
scrutiny-web        | 2025-05-04T06:13:04.918181151Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:158 +0x774
scrutiny-web        | 2025-05-04T06:13:59.203040388Z 2025/05/04 06:13:59 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.
scrutiny-web        | 2025-05-04T06:13:59.203066662Z 
scrutiny-web        | 2025-05-04T06:13:59.203105864Z  ___   ___  ____  __  __  ____  ____  _  _  _  _
scrutiny-web        | 2025-05-04T06:13:59.203115926Z / __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
scrutiny-web        | 2025-05-04T06:13:59.203124770Z \__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
scrutiny-web        | 2025-05-04T06:13:59.203133690Z (___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
scrutiny-web        | 2025-05-04T06:13:59.203141888Z github.com/AnalogJ/scrutiny                             dev-0.8.1
scrutiny-web        | 2025-05-04T06:13:59.203150325Z 
scrutiny-web        | 2025-05-04T06:13:59.203160987Z Start the scrutiny server
scrutiny-web        | 2025-05-04T06:13:59.203568157Z time="2025-05-04T06:13:59Z" level=info msg="Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:13:59.204664245Z time="2025-05-04T06:13:59Z" level=info msg="Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:13:59.204721561Z time="2025-05-04T06:13:59Z" level=info msg="InfluxDB certificate verification: true\n" type=web
scrutiny-web        | 2025-05-04T06:13:59.235871652Z time="2025-05-04T06:13:59Z" level=info msg="Database migration starting. Please wait, this process may take a long time...." type=web
scrutiny-web        | 2025-05-04T06:13:59.238666983Z 
scrutiny-web        | 2025-05-04T06:13:59.238698771Z 2025/05/04 06:13:59 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_migrations.go:409 attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:13:59.238719908Z [0.201ms] [rows:0] ALTER TABLE `devices` ADD `archived` numeric
scrutiny-web        | 2025-05-04T06:13:59.238725173Z time="2025-05-04T06:13:59Z" level=error msg="Database migration failed with error. \n Please open a github issue at https://github.com/AnalogJ/scrutiny and attach a copy of your scrutiny.db file. \n attempt to write a readonly database (8)" type=web
scrutiny-web        | 2025-05-04T06:13:59.240850390Z panic: attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:13:59.240870869Z 
scrutiny-web        | 2025-05-04T06:13:59.240877452Z goroutine 1 [running]:
scrutiny-web        | 2025-05-04T06:13:59.240883297Z github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x11d5768?, 0xc000132d80?}, {0x11d9e70?, 0xc00044d880?})
scrutiny-web        | 2025-05-04T06:13:59.240889396Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:15 +0xd6
scrutiny-web        | 2025-05-04T06:13:59.240895281Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc00012b2f0, 0x1046d81?)
scrutiny-web        | 2025-05-04T06:13:59.240907061Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xa5
scrutiny-web        | 2025-05-04T06:13:59.240912989Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc00012b2f0)
scrutiny-web        | 2025-05-04T06:13:59.240934198Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:84 +0x12c
scrutiny-web        | 2025-05-04T06:13:59.240939035Z main.main.func2(0xc000349f80)
scrutiny-web        | 2025-05-04T06:13:59.240942773Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:133 +0x39c
scrutiny-web        | 2025-05-04T06:13:59.240946727Z github.com/urfave/cli/v2.(*Command).Run(0xc0003a1320, 0xc000349e00)
scrutiny-web        | 2025-05-04T06:13:59.240951850Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x5c8
scrutiny-web        | 2025-05-04T06:13:59.240956147Z github.com/urfave/cli/v2.(*App).RunContext(0xc00037a480, {0x11ccb68?, 0xc000136020}, {0xc000134000, 0x2, 0x2})
scrutiny-web        | 2025-05-04T06:13:59.240963635Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0xbac
scrutiny-web        | 2025-05-04T06:13:59.240970417Z github.com/urfave/cli/v2.(*App).Run(...)
scrutiny-web        | 2025-05-04T06:13:59.240976182Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
scrutiny-web        | 2025-05-04T06:13:59.240981714Z main.main()
scrutiny-web        | 2025-05-04T06:13:59.240987774Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:158 +0x774
scrutiny-web        | 2025-05-04T06:15:00.129557115Z 2025/05/04 06:15:00 No configuration file found at /opt/scrutiny/config/scrutiny.yaml. Using Defaults.
scrutiny-web        | 2025-05-04T06:15:00.129602242Z 
scrutiny-web        | 2025-05-04T06:15:00.129631819Z  ___   ___  ____  __  __  ____  ____  _  _  _  _
scrutiny-web        | 2025-05-04T06:15:00.129638674Z / __) / __)(  _ \(  )(  )(_  _)(_  _)( \( )( \/ )
scrutiny-web        | 2025-05-04T06:15:00.129644694Z \__ \( (__  )   / )(__)(   )(   _)(_  )  (  \  /
scrutiny-web        | 2025-05-04T06:15:00.129650328Z (___/ \___)(_)\_)(______) (__) (____)(_)\_) (__)
scrutiny-web        | 2025-05-04T06:15:00.129656038Z github.com/AnalogJ/scrutiny                             dev-0.8.1
scrutiny-web        | 2025-05-04T06:15:00.129661550Z 
scrutiny-web        | 2025-05-04T06:15:00.129666805Z Start the scrutiny server
scrutiny-web        | 2025-05-04T06:15:00.129793540Z time="2025-05-04T06:15:00Z" level=info msg="Trying to connect to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:15:00.130566488Z time="2025-05-04T06:15:00Z" level=info msg="Successfully connected to scrutiny sqlite db: /opt/scrutiny/config/scrutiny.db\n" type=web
scrutiny-web        | 2025-05-04T06:15:00.130588217Z time="2025-05-04T06:15:00Z" level=info msg="InfluxDB certificate verification: true\n" type=web
scrutiny-web        | 2025-05-04T06:15:00.191936182Z time="2025-05-04T06:15:00Z" level=info msg="Database migration starting. Please wait, this process may take a long time...." type=web
scrutiny-web        | 2025-05-04T06:15:00.195113196Z 
scrutiny-web        | 2025-05-04T06:15:00.195135423Z 2025/05/04 06:15:00 /go/src/github.com/analogj/scrutiny/webapp/backend/pkg/database/scrutiny_repository_migrations.go:409 attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:15:00.195145268Z [0.227ms] [rows:0] ALTER TABLE `devices` ADD `archived` numeric
scrutiny-web        | 2025-05-04T06:15:00.195159770Z time="2025-05-04T06:15:00Z" level=error msg="Database migration failed with error. \n Please open a github issue at https://github.com/AnalogJ/scrutiny and attach a copy of your scrutiny.db file. \n attempt to write a readonly database (8)" type=web
scrutiny-web        | 2025-05-04T06:15:00.197313348Z panic: attempt to write a readonly database (8)
scrutiny-web        | 2025-05-04T06:15:00.197324608Z 
scrutiny-web        | 2025-05-04T06:15:00.197328910Z goroutine 1 [running]:
scrutiny-web        | 2025-05-04T06:15:00.197332886Z github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware.RepositoryMiddleware({0x11d5768?, 0xc000014d90?}, {0x11d9e70?, 0xc000455880?})
scrutiny-web        | 2025-05-04T06:15:00.197358158Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/middleware/repository.go:15 +0xd6
scrutiny-web        | 2025-05-04T06:15:00.197375375Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Setup(0xc000013308, 0x1046d81?)
scrutiny-web        | 2025-05-04T06:15:00.197383604Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:26 +0xa5
scrutiny-web        | 2025-05-04T06:15:00.197391474Z github.com/analogj/scrutiny/webapp/backend/pkg/web.(*AppEngine).Start(0xc000013308)
scrutiny-web        | 2025-05-04T06:15:00.197396077Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/pkg/web/server.go:84 +0x12c
scrutiny-web        | 2025-05-04T06:15:00.197405286Z main.main.func2(0xc000355f80)
scrutiny-web        | 2025-05-04T06:15:00.197409603Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:133 +0x39c
scrutiny-web        | 2025-05-04T06:15:00.197413991Z github.com/urfave/cli/v2.(*Command).Run(0xc0003ab320, 0xc000355e00)
scrutiny-web        | 2025-05-04T06:15:00.197418078Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/command.go:164 +0x5c8
scrutiny-web        | 2025-05-04T06:15:00.197423208Z github.com/urfave/cli/v2.(*App).RunContext(0xc00031e600, {0x11ccb68?, 0xc000046050}, {0xc000036040, 0x2, 0x2})
scrutiny-web        | 2025-05-04T06:15:00.197434216Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:306 +0xbac
scrutiny-web        | 2025-05-04T06:15:00.197439538Z github.com/urfave/cli/v2.(*App).Run(...)
scrutiny-web        | 2025-05-04T06:15:00.197445201Z 	/go/src/github.com/analogj/scrutiny/vendor/github.com/urfave/cli/v2/app.go:215
scrutiny-web        | 2025-05-04T06:15:00.197449190Z main.main()
scrutiny-web        | 2025-05-04T06:15:00.197453760Z 	/go/src/github.com/analogj/scrutiny/webapp/backend/cmd/scrutiny/scrutiny.go:158 +0x774
```
