### ISSUE TITLE
[FEAT] docker-compose example

### ISSUE THREAD

**Issue by Motophan** [AnalogJ/scrutiny#90]
**Is your feature request related to a problem? Please describe.**
I cant figure out hot to pass --device=/dev/sda in docker-compose format

**Describe the solution you'd like**
something like
```
  scrutiny:
    image: analogj/scrutiny:latest
    container_name: scrutiny
    restart: always
    networks:
      - yeetmaster
    volumes:
      - $USERDIR/docker/scrutiny:/config
      - /run/udev:/run/udev:ro
    restart: unless-stopped
    environment:
    devices:
      - --device=/dev/sda
      - --device=/dev/sdb
      - --device=/dev/sdc
      - --device=/dev/sdd
      - --device=/dev/sde
      - --device=/dev/sdf
      - --device=/dev/sdg
      - --device=/dev/sdh
      - --device=/dev/sdi
      - --device=/dev/sdj
      - --device=/dev/sdk
      - --device=/dev/sdl
      - --device=/dev/nvme0n1
      - --device=/dev/nvme1n1
    cap_add:
      - SYS_RAWIO
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.scrutiny-rtr.entrypoints=https"
      - "traefik.http.routers.scrutiny-rtr.rule=Host(`scrutiny.$DOMAINNAME`)"
      - "traefik.http.routers.scrutiny-rtr.tls=true"
#      ## Middlewares
##      - "traefik.http.routers.jackett-rtr.middlewares=chain-basic-auth@file"
#      ## HTTP Services
      - "traefik.http.routers.scrutiny-rtr.service=scrutiny-svc"
      - "traefik.http.services.scrutiny-svc.loadbalancer.server.port=8080"
```

But be correct.

This will pass the yml checker but wont show any drives. I am unsure if this is a compose issue and I am not passing the devices properly, or if it is a os issue (I dont have smartd installed).
