### ISSUE TITLE
[BUG] Synology and smartctl

### ISSUE THREAD

**Issue by fnoir** [AnalogJ/scrutiny#96]
**Describe the bug**
I use scrutiny (docker-compose) with a Synology DS1618+ (6 drives)
I have an error with command `docker exec scrutiny scrutiny-collector-metrics run`:

```
time="2020-10-09T14:05:57Z" level=error msg="smartctl returned an error code (4) while processing sda\n" type=metrics
time="2020-10-09T14:05:57Z" level=error msg="smartctl detected a checksum error" type=metrics
time="2020-10-09T14:05:57Z" level=info msg="Publishing smartctl results for unknown\n" type=metrics
```

docker-compose.yml
```
scrutiny:
    image: analogj/scrutiny:latest
    container_name: scrutiny
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
    ports:
      - "8080:8080"
    volumes:
      - ./appdata/scrutiny:/scrutiny/config
      - /run/udev:/run/udev:ro
```

**Comment by AnalogJ** [comment]
Hey @fnoir 

Can you confirm that `smartctl` works correctly on your host, without running scrutiny?

Please attach the output of the following commands:

```
smartctl -j --scan 
smartctl -x -j /dev/sda
smartctl -x -j -d sat /dev/sda
```

**Comment by fnoir** [comment]
Hey,
same error for all:

```
smartctl 6.5 (build date May  7 2020) [x86_64-linux-4.4.59+] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=======> UNRECOGNIZED OPTION: j

Use smartctl -h to get a usage summary
```

**Comment by arnauos** [comment]
"-j" does not seem to work with the Synology bundled version of smartctl.

create a collector.yaml inside the config folder of the docker with these contents and try again:

```
version: 1
devices:
  - device: /dev/sda
    type: 'sat'
  - device: /dev/sdb
    type: 'sat'
  - device: /dev/sdc
    type: 'sat'
  - device: /dev/sdd
    type: 'sat'
  - device: /dev/sde
    type: 'sat'
  - device: /dev/sdf
    type: 'sat'
```
